/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catalogEntriesListInfrastructures } from "../../funcs/catalogEntriesListInfrastructures.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListInfrastructuresRequest$inboundSchema,
};

export const tool$catalogEntriesListInfrastructures: ToolDefinition<
  typeof args
> = {
  name: "catalog-entries-list-infrastructures",
  description: `Lists functionality, service and environment objects

Lists functionality, service and environment objects`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await catalogEntriesListInfrastructures(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
