/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catalogEntriesListServiceAvailableDownstreamDependencies } from "../../funcs/catalogEntriesListServiceAvailableDownstreamDependencies.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.ListServiceAvailableDownstreamDependenciesRequest$inboundSchema,
};

export const tool$catalogEntriesListServiceAvailableDownstreamDependencies:
  ToolDefinition<typeof args> = {
    name: "catalog-entries-list-service-available-downstream-dependencies",
    description: `List available downstream service dependencies

Retrieves all services that are available to be downstream dependencies`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await catalogEntriesListServiceAvailableDownstreamDependencies(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
