/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsListCommentReactions } from "../../funcs/conversationsListCommentReactions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListCommentReactionsRequest$inboundSchema,
};

export const tool$conversationsListCommentReactions: ToolDefinition<
  typeof args
> = {
  name: "conversations-list-comment-reactions",
  description: `List reactions for a conversation comment

List all of the reactions that have been added to a comment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await conversationsListCommentReactions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
