/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsCreateCommentReaction } from "../../funcs/conversationsCreateCommentReaction.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCommentReactionRequest$inboundSchema,
};

export const tool$conversationsCreateCommentReaction: ToolDefinition<
  typeof args
> = {
  name: "conversations-create-comment-reaction",
  description: `Create a reaction for a conversation comment

Create a reaction on a comment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await conversationsCreateCommentReaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
