/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsCreateIncidentTeamAssignment } from "../../funcs/incidentsCreateIncidentTeamAssignment.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateIncidentTeamAssignmentRequest$inboundSchema,
};

export const tool$incidentsCreateIncidentTeamAssignment: ToolDefinition<
  typeof args
> = {
  name: "incidents-create-incident-team-assignment",
  description: `Assign a team to an incident

Assign a team for this incident`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsCreateIncidentTeamAssignment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
