/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsUpdateIncidentNote } from "../../funcs/incidentsUpdateIncidentNote.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateIncidentNoteRequest$inboundSchema,
};

export const tool$incidentsUpdateIncidentNote: ToolDefinition<typeof args> = {
  name: "incidents-update-incident-note",
  description: `Update a note

Updates the body of a note`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsUpdateIncidentNote(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
