/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentSettingsUpdateSeverity } from "../../funcs/incidentSettingsUpdateSeverity.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateSeverityRequest$inboundSchema,
};

export const tool$incidentSettingsUpdateSeverity: ToolDefinition<typeof args> =
  {
    name: "incident-settings-update-severity",
    description: `Update a severity

Update a specific severity`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await incidentSettingsUpdateSeverity(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
