/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsGetIncidentEvent } from "../../funcs/incidentsGetIncidentEvent.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetIncidentEventRequest$inboundSchema,
};

export const tool$incidentsGetIncidentEvent: ToolDefinition<typeof args> = {
  name: "incidents-get-incident-event",
  description: `Get an incident event

Retrieve a single event for an incident`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsGetIncidentEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
