/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentSettingsListIncidentTags } from "../../funcs/incidentSettingsListIncidentTags.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListIncidentTagsRequest$inboundSchema,
};

export const tool$incidentSettingsListIncidentTags: ToolDefinition<
  typeof args
> = {
  name: "incident-settings-list-incident-tags",
  description: `List incident tags

List all of the incident tags in the organization`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentSettingsListIncidentTags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
