/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsGetIncidentChannel } from "../../funcs/incidentsGetIncidentChannel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetIncidentChannelRequest$inboundSchema,
};

export const tool$incidentsGetIncidentChannel: ToolDefinition<typeof args> = {
  name: "incidents-get-incident-channel",
  description: `Get chat channel information for an incident

Gives chat channel information for the specified incident`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await incidentsGetIncidentChannel(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
