/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsListSlackWorkspaces } from "../../funcs/integrationsListSlackWorkspaces.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListSlackWorkspacesRequest$inboundSchema,
};

export const tool$integrationsListSlackWorkspaces: ToolDefinition<typeof args> =
  {
    name: "integrations-list-slack-workspaces",
    description: `List Slack workspaces

Lists all Slack workspaces`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await integrationsListSlackWorkspaces(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
