/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetSlackEmojiAction } from "../../funcs/integrationsGetSlackEmojiAction.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSlackEmojiActionRequest$inboundSchema,
};

export const tool$integrationsGetSlackEmojiAction: ToolDefinition<typeof args> =
  {
    name: "integrations-get-slack-emoji-action",
    description: `Get a Slack emoji action

Retrieves a Slack emoji action`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await integrationsGetSlackEmojiAction(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
