/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsListSlackUsergroups } from "../../funcs/integrationsListSlackUsergroups.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$integrationsListSlackUsergroups: ToolDefinition = {
  name: "integrations-list-slack-usergroups",
  description: `List Slack user groups

Lists all Slack user groups`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await integrationsListSlackUsergroups(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
