/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsUpdateStatuspageConnection } from "../../funcs/integrationsUpdateStatuspageConnection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateStatuspageConnectionRequest$inboundSchema,
};

export const tool$integrationsUpdateStatuspageConnection: ToolDefinition<
  typeof args
> = {
  name: "integrations-update-statuspage-connection",
  description: `Update a Statuspage connection

Update the given Statuspage integration connection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsUpdateStatuspageConnection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
