/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetAwsConnection } from "../../funcs/integrationsGetAwsConnection.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAwsConnectionRequest$inboundSchema,
};

export const tool$integrationsGetAwsConnection: ToolDefinition<typeof args> = {
  name: "integrations-get-aws-connection",
  description: `Get an AWS connection

Retrieves the information about the AWS connection.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsGetAwsConnection(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
