/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetAwsCloudtrailBatch } from "../../funcs/integrationsGetAwsCloudtrailBatch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAwsCloudtrailBatchRequest$inboundSchema,
};

export const tool$integrationsGetAwsCloudtrailBatch: ToolDefinition<
  typeof args
> = {
  name: "integrations-get-aws-cloudtrail-batch",
  description: `Get a CloudTrail batch

Retrieve a single CloudTrail batch.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsGetAwsCloudtrailBatch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
