/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsListAwsCloudtrailBatches } from "../../funcs/integrationsListAwsCloudtrailBatches.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAwsCloudtrailBatchesRequest$inboundSchema,
};

export const tool$integrationsListAwsCloudtrailBatches: ToolDefinition<
  typeof args
> = {
  name: "integrations-list-aws-cloudtrail-batches",
  description: `List CloudTrail batches

Lists CloudTrail batches for the authenticated organization.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsListAwsCloudtrailBatches(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
