/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { retrospectivesUpdatePostMortemQuestions } from "../../funcs/retrospectivesUpdatePostMortemQuestions.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.UpdatePostMortemQuestions$inboundSchema,
};

export const tool$retrospectivesUpdatePostMortemQuestions: ToolDefinition<
  typeof args
> = {
  name: "retrospectives-update-post-mortem-questions",
  description: `Update retrospective questions

Update the questions configured to be provided and filled out on future retrospective reports.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await retrospectivesUpdatePostMortemQuestions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
