/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runbooksDeleteRunbook } from "../../funcs/runbooksDeleteRunbook.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteRunbookRequest$inboundSchema,
};

export const tool$runbooksDeleteRunbook: ToolDefinition<typeof args> = {
  name: "runbooks-delete-runbook",
  description: `Delete a runbook

Delete a runbook and make it unavailable for any future incidents.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await runbooksDeleteRunbook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
