/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scimUpdateSCIMUser } from "../../funcs/scimUpdateSCIMUser.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateScimUserRequest$inboundSchema,
};

export const tool$scimUpdateSCIMUser: ToolDefinition<typeof args> = {
  name: "scim-update-scim-user",
  description: `Update a User from SCIM data

PUT SCIM endpoint to update a User. This endpoint is used to replace a resource's attributes.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scimUpdateSCIMUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
