/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scimDeleteSCIMUser } from "../../funcs/scimDeleteSCIMUser.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteScimUserRequest$inboundSchema,
};

export const tool$scimDeleteSCIMUser: ToolDefinition<typeof args> = {
  name: "scim-delete-scim-user",
  description: `Delete a User matching SCIM data

SCIM endpoint to delete a User. This endpoint will deactivate a confirmed User record in our system.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await scimDeleteSCIMUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
