/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signalsCreateSignalsWebhookTarget } from "../../funcs/signalsCreateSignalsWebhookTarget.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateSignalsWebhookTarget$inboundSchema,
};

export const tool$signalsCreateSignalsWebhookTarget: ToolDefinition<
  typeof args
> = {
  name: "signals-create-signals-webhook-target",
  description: `Create a webhook target

Create a Signals webhook target.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await signalsCreateSignalsWebhookTarget(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
