/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signalsGetTeamSignalRule } from "../../funcs/signalsGetTeamSignalRule.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTeamSignalRuleRequest$inboundSchema,
};

export const tool$signalsGetTeamSignalRule: ToolDefinition<typeof args> = {
  name: "signals-get-team-signal-rule",
  description: `Get a Signals rule

Get a Signals rule by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await signalsGetTeamSignalRule(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
