/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signalsListTeamOnCallSchedules } from "../../funcs/signalsListTeamOnCallSchedules.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTeamOnCallSchedulesRequest$inboundSchema,
};

export const tool$signalsListTeamOnCallSchedules: ToolDefinition<typeof args> =
  {
    name: "signals-list-team-on-call-schedules",
    description: `List on-call schedules for a team

List all Signals on-call schedules for a team.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await signalsListTeamOnCallSchedules(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
