/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signalsDeleteSignalsAlertGroupingConfiguration } from "../../funcs/signalsDeleteSignalsAlertGroupingConfiguration.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.DeleteSignalsAlertGroupingConfigurationRequest$inboundSchema,
};

export const tool$signalsDeleteSignalsAlertGroupingConfiguration:
  ToolDefinition<typeof args> = {
    name: "signals-delete-signals-alert-grouping-configuration",
    description: `Delete an alert grouping configuration.

Delete a Signals alert grouping rule by ID.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await signalsDeleteSignalsAlertGroupingConfiguration(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
