/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusPagesCreateEmailSubscriber } from "../../funcs/statusPagesCreateEmailSubscriber.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateEmailSubscriberRequest$inboundSchema,
};

export const tool$statusPagesCreateEmailSubscriber: ToolDefinition<
  typeof args
> = {
  name: "status-pages-create-email-subscriber",
  description: `Add subscribers to a status page

Subscribes a comma-separated string of emails to status page updates`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await statusPagesCreateEmailSubscriber(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
