/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusPagesUpdateNuncImage } from "../../funcs/statusPagesUpdateNuncImage.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateNuncImageRequest$inboundSchema,
};

export const tool$statusPagesUpdateNuncImage: ToolDefinition<typeof args> = {
  name: "status-pages-update-nunc-image",
  description: `Upload an image for a status page

Add or replace an image attached to a FireHydrant status page`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await statusPagesUpdateNuncImage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
