/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksConvertIncidentTask } from "../../funcs/tasksConvertIncidentTask.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ConvertIncidentTaskRequest$inboundSchema,
};

export const tool$tasksConvertIncidentTask: ToolDefinition<typeof args> = {
  name: "tasks-convert-incident-task",
  description: `Convert a task to a follow-up

Convert a task to a follow-up`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksConvertIncidentTask(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
