/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksCreateIncidentTaskList } from "../../funcs/tasksCreateIncidentTaskList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateIncidentTaskListRequest$inboundSchema,
};

export const tool$tasksCreateIncidentTaskList: ToolDefinition<typeof args> = {
  name: "tasks-create-incident-task-list",
  description: `Add tasks from a task list to an incident

Add all tasks from list to incident`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksCreateIncidentTaskList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
