/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ticketingListTicketingCustomDefinitions } from "../../funcs/ticketingListTicketingCustomDefinitions.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$ticketingListTicketingCustomDefinitions: ToolDefinition = {
  name: "ticketing-list-ticketing-custom-definitions",
  description: `List ticketing custom fields

List all ticketing custom fields available to the organization`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await ticketingListTicketingCustomDefinitions(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
