/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ticketingGetTicket } from "../../funcs/ticketingGetTicket.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTicketRequest$inboundSchema,
};

export const tool$ticketingGetTicket: ToolDefinition<typeof args> = {
  name: "ticketing-get-ticket",
  description: `Get a ticket

Retrieves a single ticket by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ticketingGetTicket(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
