/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ticketingListTickets } from "../../funcs/ticketingListTickets.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTicketsRequest$inboundSchema,
};

export const tool$ticketingListTickets: ToolDefinition<typeof args> = {
  name: "ticketing-list-tickets",
  description: `List tickets

List all of the tickets that have been added to the organiation`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ticketingListTickets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
