/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ticketingUpdateTicketingCustomDefinition } from "../../funcs/ticketingUpdateTicketingCustomDefinition.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateTicketingCustomDefinitionRequest$inboundSchema,
};

export const tool$ticketingUpdateTicketingCustomDefinition: ToolDefinition<
  typeof args
> = {
  name: "ticketing-update-ticketing-custom-definition",
  description: `Update a ticketing custom field

Update a ticketing custom field for the organization`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ticketingUpdateTicketingCustomDefinition(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
