workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    firehydrant-oas:
        inputs:
            - location: ./openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: errors-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-oas
targets:
    firehydrant-typescript-sdk:
        target: typescript
        source: firehydrant-oas
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-typescript-sdk-oas-code-samples
            blocking: false
