workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    firehydrant-typescript-sdk-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-oas:main
targets:
    firehydrant-typescript-sdk:
        target: typescript
        source: firehydrant-typescript-sdk-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-typescript-sdk-oas-code-samples
            blocking: false
