/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The group method of notification that will be delivered.
 */
export const CreateHandoffNotificationSettingNotificationGroupMethod = {
  Any: "any",
  Push: "push",
  Email: "email",
  Voice: "voice",
  MobileText: "mobile_text",
  Chat: "chat",
} as const;
/**
 * The group method of notification that will be delivered.
 */
export type CreateHandoffNotificationSettingNotificationGroupMethod =
  ClosedEnum<typeof CreateHandoffNotificationSettingNotificationGroupMethod>;

/**
 * The priority of the notification.
 */
export const CreateHandoffNotificationSettingPriority = {
  High: "HIGH",
  Medium: "MEDIUM",
  Low: "LOW",
} as const;
/**
 * The priority of the notification.
 */
export type CreateHandoffNotificationSettingPriority = ClosedEnum<
  typeof CreateHandoffNotificationSettingPriority
>;

export type CreateHandoffNotificationSettingRequest = {
  /**
   * The group method of notification that will be delivered.
   */
  notificationGroupMethod:
    CreateHandoffNotificationSettingNotificationGroupMethod;
  /**
   * An ISO8601 duration string specifying the maximum delay of the notification.
   */
  maxDelay: string;
  /**
   * The priority of the notification.
   */
  priority: CreateHandoffNotificationSettingPriority;
};

/** @internal */
export const CreateHandoffNotificationSettingNotificationGroupMethod$inboundSchema:
  z.ZodNativeEnum<
    typeof CreateHandoffNotificationSettingNotificationGroupMethod
  > = z.nativeEnum(CreateHandoffNotificationSettingNotificationGroupMethod);

/** @internal */
export const CreateHandoffNotificationSettingNotificationGroupMethod$outboundSchema:
  z.ZodNativeEnum<
    typeof CreateHandoffNotificationSettingNotificationGroupMethod
  > = CreateHandoffNotificationSettingNotificationGroupMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateHandoffNotificationSettingNotificationGroupMethod$ {
  /** @deprecated use `CreateHandoffNotificationSettingNotificationGroupMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateHandoffNotificationSettingNotificationGroupMethod$inboundSchema;
  /** @deprecated use `CreateHandoffNotificationSettingNotificationGroupMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateHandoffNotificationSettingNotificationGroupMethod$outboundSchema;
}

/** @internal */
export const CreateHandoffNotificationSettingPriority$inboundSchema:
  z.ZodNativeEnum<typeof CreateHandoffNotificationSettingPriority> = z
    .nativeEnum(CreateHandoffNotificationSettingPriority);

/** @internal */
export const CreateHandoffNotificationSettingPriority$outboundSchema:
  z.ZodNativeEnum<typeof CreateHandoffNotificationSettingPriority> =
    CreateHandoffNotificationSettingPriority$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateHandoffNotificationSettingPriority$ {
  /** @deprecated use `CreateHandoffNotificationSettingPriority$inboundSchema` instead. */
  export const inboundSchema =
    CreateHandoffNotificationSettingPriority$inboundSchema;
  /** @deprecated use `CreateHandoffNotificationSettingPriority$outboundSchema` instead. */
  export const outboundSchema =
    CreateHandoffNotificationSettingPriority$outboundSchema;
}

/** @internal */
export const CreateHandoffNotificationSettingRequest$inboundSchema: z.ZodType<
  CreateHandoffNotificationSettingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  notification_group_method:
    CreateHandoffNotificationSettingNotificationGroupMethod$inboundSchema,
  max_delay: z.string(),
  priority: CreateHandoffNotificationSettingPriority$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "notification_group_method": "notificationGroupMethod",
    "max_delay": "maxDelay",
  });
});

/** @internal */
export type CreateHandoffNotificationSettingRequest$Outbound = {
  notification_group_method: string;
  max_delay: string;
  priority: string;
};

/** @internal */
export const CreateHandoffNotificationSettingRequest$outboundSchema: z.ZodType<
  CreateHandoffNotificationSettingRequest$Outbound,
  z.ZodTypeDef,
  CreateHandoffNotificationSettingRequest
> = z.object({
  notificationGroupMethod:
    CreateHandoffNotificationSettingNotificationGroupMethod$outboundSchema,
  maxDelay: z.string(),
  priority: CreateHandoffNotificationSettingPriority$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    notificationGroupMethod: "notification_group_method",
    maxDelay: "max_delay",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateHandoffNotificationSettingRequest$ {
  /** @deprecated use `CreateHandoffNotificationSettingRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateHandoffNotificationSettingRequest$inboundSchema;
  /** @deprecated use `CreateHandoffNotificationSettingRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateHandoffNotificationSettingRequest$outboundSchema;
  /** @deprecated use `CreateHandoffNotificationSettingRequest$Outbound` instead. */
  export type Outbound = CreateHandoffNotificationSettingRequest$Outbound;
}

export function createHandoffNotificationSettingRequestToJSON(
  createHandoffNotificationSettingRequest:
    CreateHandoffNotificationSettingRequest,
): string {
  return JSON.stringify(
    CreateHandoffNotificationSettingRequest$outboundSchema.parse(
      createHandoffNotificationSettingRequest,
    ),
  );
}

export function createHandoffNotificationSettingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateHandoffNotificationSettingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateHandoffNotificationSettingRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateHandoffNotificationSettingRequest' from JSON`,
  );
}
