/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateIncidentNoteRequest = {
  incidentId: string;
  createIncidentNote: components.CreateIncidentNote;
};

/** @internal */
export const CreateIncidentNoteRequest$inboundSchema: z.ZodType<
  CreateIncidentNoteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
  create_incident_note: z.lazy(() =>
    components.CreateIncidentNote$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
    "create_incident_note": "createIncidentNote",
  });
});
/** @internal */
export type CreateIncidentNoteRequest$Outbound = {
  incident_id: string;
  create_incident_note: components.CreateIncidentNote$Outbound;
};

/** @internal */
export const CreateIncidentNoteRequest$outboundSchema: z.ZodType<
  CreateIncidentNoteRequest$Outbound,
  z.ZodTypeDef,
  CreateIncidentNoteRequest
> = z.object({
  incidentId: z.string(),
  createIncidentNote: z.lazy(() =>
    components.CreateIncidentNote$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
    createIncidentNote: "create_incident_note",
  });
});

export function createIncidentNoteRequestToJSON(
  createIncidentNoteRequest: CreateIncidentNoteRequest,
): string {
  return JSON.stringify(
    CreateIncidentNoteRequest$outboundSchema.parse(createIncidentNoteRequest),
  );
}
export function createIncidentNoteRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateIncidentNoteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateIncidentNoteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateIncidentNoteRequest' from JSON`,
  );
}
