/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRunbookRequest = {
  runbookId: string;
};

/** @internal */
export const DeleteRunbookRequest$inboundSchema: z.ZodType<
  DeleteRunbookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  runbook_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "runbook_id": "runbookId",
  });
});

/** @internal */
export type DeleteRunbookRequest$Outbound = {
  runbook_id: string;
};

/** @internal */
export const DeleteRunbookRequest$outboundSchema: z.ZodType<
  DeleteRunbookRequest$Outbound,
  z.ZodTypeDef,
  DeleteRunbookRequest
> = z.object({
  runbookId: z.string(),
}).transform((v) => {
  return remap$(v, {
    runbookId: "runbook_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRunbookRequest$ {
  /** @deprecated use `DeleteRunbookRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteRunbookRequest$inboundSchema;
  /** @deprecated use `DeleteRunbookRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteRunbookRequest$outboundSchema;
  /** @deprecated use `DeleteRunbookRequest$Outbound` instead. */
  export type Outbound = DeleteRunbookRequest$Outbound;
}

export function deleteRunbookRequestToJSON(
  deleteRunbookRequest: DeleteRunbookRequest,
): string {
  return JSON.stringify(
    DeleteRunbookRequest$outboundSchema.parse(deleteRunbookRequest),
  );
}

export function deleteRunbookRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRunbookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRunbookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRunbookRequest' from JSON`,
  );
}
