/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTicketingProjectConfigRequest = {
  ticketingProjectId: string;
  configId: string;
};

/** @internal */
export const DeleteTicketingProjectConfigRequest$inboundSchema: z.ZodType<
  DeleteTicketingProjectConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ticketing_project_id: z.string(),
  config_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "ticketing_project_id": "ticketingProjectId",
    "config_id": "configId",
  });
});
/** @internal */
export type DeleteTicketingProjectConfigRequest$Outbound = {
  ticketing_project_id: string;
  config_id: string;
};

/** @internal */
export const DeleteTicketingProjectConfigRequest$outboundSchema: z.ZodType<
  DeleteTicketingProjectConfigRequest$Outbound,
  z.ZodTypeDef,
  DeleteTicketingProjectConfigRequest
> = z.object({
  ticketingProjectId: z.string(),
  configId: z.string(),
}).transform((v) => {
  return remap$(v, {
    ticketingProjectId: "ticketing_project_id",
    configId: "config_id",
  });
});

export function deleteTicketingProjectConfigRequestToJSON(
  deleteTicketingProjectConfigRequest: DeleteTicketingProjectConfigRequest,
): string {
  return JSON.stringify(
    DeleteTicketingProjectConfigRequest$outboundSchema.parse(
      deleteTicketingProjectConfigRequest,
    ),
  );
}
export function deleteTicketingProjectConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTicketingProjectConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteTicketingProjectConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTicketingProjectConfigRequest' from JSON`,
  );
}
