/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteEnvironmentRequest = {
  /**
   * Environment UUID
   */
  environmentId: string;
};

/** @internal */
export const DeleteEnvironmentRequest$inboundSchema: z.ZodType<
  DeleteEnvironmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  environment_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "environment_id": "environmentId",
  });
});
/** @internal */
export type DeleteEnvironmentRequest$Outbound = {
  environment_id: string;
};

/** @internal */
export const DeleteEnvironmentRequest$outboundSchema: z.ZodType<
  DeleteEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  DeleteEnvironmentRequest
> = z.object({
  environmentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    environmentId: "environment_id",
  });
});

export function deleteEnvironmentRequestToJSON(
  deleteEnvironmentRequest: DeleteEnvironmentRequest,
): string {
  return JSON.stringify(
    DeleteEnvironmentRequest$outboundSchema.parse(deleteEnvironmentRequest),
  );
}
export function deleteEnvironmentRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEnvironmentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEnvironmentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEnvironmentRequest' from JSON`,
  );
}
