/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAwsCloudtrailBatchEventsRequest = {
  id: string;
};

/** @internal */
export const GetAwsCloudtrailBatchEventsRequest$inboundSchema: z.ZodType<
  GetAwsCloudtrailBatchEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetAwsCloudtrailBatchEventsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAwsCloudtrailBatchEventsRequest$outboundSchema: z.ZodType<
  GetAwsCloudtrailBatchEventsRequest$Outbound,
  z.ZodTypeDef,
  GetAwsCloudtrailBatchEventsRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAwsCloudtrailBatchEventsRequest$ {
  /** @deprecated use `GetAwsCloudtrailBatchEventsRequest$inboundSchema` instead. */
  export const inboundSchema = GetAwsCloudtrailBatchEventsRequest$inboundSchema;
  /** @deprecated use `GetAwsCloudtrailBatchEventsRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetAwsCloudtrailBatchEventsRequest$outboundSchema;
  /** @deprecated use `GetAwsCloudtrailBatchEventsRequest$Outbound` instead. */
  export type Outbound = GetAwsCloudtrailBatchEventsRequest$Outbound;
}

export function getAwsCloudtrailBatchEventsRequestToJSON(
  getAwsCloudtrailBatchEventsRequest: GetAwsCloudtrailBatchEventsRequest,
): string {
  return JSON.stringify(
    GetAwsCloudtrailBatchEventsRequest$outboundSchema.parse(
      getAwsCloudtrailBatchEventsRequest,
    ),
  );
}

export function getAwsCloudtrailBatchEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAwsCloudtrailBatchEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetAwsCloudtrailBatchEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAwsCloudtrailBatchEventsRequest' from JSON`,
  );
}
