/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAuditEventRequest = {
  id: string;
};

/** @internal */
export const GetAuditEventRequest$inboundSchema: z.ZodType<
  GetAuditEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetAuditEventRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAuditEventRequest$outboundSchema: z.ZodType<
  GetAuditEventRequest$Outbound,
  z.ZodTypeDef,
  GetAuditEventRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAuditEventRequest$ {
  /** @deprecated use `GetAuditEventRequest$inboundSchema` instead. */
  export const inboundSchema = GetAuditEventRequest$inboundSchema;
  /** @deprecated use `GetAuditEventRequest$outboundSchema` instead. */
  export const outboundSchema = GetAuditEventRequest$outboundSchema;
  /** @deprecated use `GetAuditEventRequest$Outbound` instead. */
  export type Outbound = GetAuditEventRequest$Outbound;
}

export function getAuditEventRequestToJSON(
  getAuditEventRequest: GetAuditEventRequest,
): string {
  return JSON.stringify(
    GetAuditEventRequest$outboundSchema.parse(getAuditEventRequest),
  );
}

export function getAuditEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAuditEventRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAuditEventRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAuditEventRequest' from JSON`,
  );
}
