/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFormConfigurationRequest = {
  slug: string;
};

/** @internal */
export const GetFormConfigurationRequest$inboundSchema: z.ZodType<
  GetFormConfigurationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});
/** @internal */
export type GetFormConfigurationRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetFormConfigurationRequest$outboundSchema: z.ZodType<
  GetFormConfigurationRequest$Outbound,
  z.ZodTypeDef,
  GetFormConfigurationRequest
> = z.object({
  slug: z.string(),
});

export function getFormConfigurationRequestToJSON(
  getFormConfigurationRequest: GetFormConfigurationRequest,
): string {
  return JSON.stringify(
    GetFormConfigurationRequest$outboundSchema.parse(
      getFormConfigurationRequest,
    ),
  );
}
export function getFormConfigurationRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetFormConfigurationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFormConfigurationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFormConfigurationRequest' from JSON`,
  );
}
