/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIncidentRequest = {
  incidentId: string;
};

/** @internal */
export const GetIncidentRequest$inboundSchema: z.ZodType<
  GetIncidentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
  });
});

/** @internal */
export type GetIncidentRequest$Outbound = {
  incident_id: string;
};

/** @internal */
export const GetIncidentRequest$outboundSchema: z.ZodType<
  GetIncidentRequest$Outbound,
  z.ZodTypeDef,
  GetIncidentRequest
> = z.object({
  incidentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIncidentRequest$ {
  /** @deprecated use `GetIncidentRequest$inboundSchema` instead. */
  export const inboundSchema = GetIncidentRequest$inboundSchema;
  /** @deprecated use `GetIncidentRequest$outboundSchema` instead. */
  export const outboundSchema = GetIncidentRequest$outboundSchema;
  /** @deprecated use `GetIncidentRequest$Outbound` instead. */
  export type Outbound = GetIncidentRequest$Outbound;
}

export function getIncidentRequestToJSON(
  getIncidentRequest: GetIncidentRequest,
): string {
  return JSON.stringify(
    GetIncidentRequest$outboundSchema.parse(getIncidentRequest),
  );
}

export function getIncidentRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetIncidentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIncidentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIncidentRequest' from JSON`,
  );
}
