/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIncidentChannelRequest = {
  incidentId: string;
};

/** @internal */
export const GetIncidentChannelRequest$inboundSchema: z.ZodType<
  GetIncidentChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
  });
});
/** @internal */
export type GetIncidentChannelRequest$Outbound = {
  incident_id: string;
};

/** @internal */
export const GetIncidentChannelRequest$outboundSchema: z.ZodType<
  GetIncidentChannelRequest$Outbound,
  z.ZodTypeDef,
  GetIncidentChannelRequest
> = z.object({
  incidentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
  });
});

export function getIncidentChannelRequestToJSON(
  getIncidentChannelRequest: GetIncidentChannelRequest,
): string {
  return JSON.stringify(
    GetIncidentChannelRequest$outboundSchema.parse(getIncidentChannelRequest),
  );
}
export function getIncidentChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetIncidentChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIncidentChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIncidentChannelRequest' from JSON`,
  );
}
