/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetScheduledMaintenanceRequest = {
  scheduledMaintenanceId: string;
};

/** @internal */
export const GetScheduledMaintenanceRequest$inboundSchema: z.ZodType<
  GetScheduledMaintenanceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduled_maintenance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "scheduled_maintenance_id": "scheduledMaintenanceId",
  });
});

/** @internal */
export type GetScheduledMaintenanceRequest$Outbound = {
  scheduled_maintenance_id: string;
};

/** @internal */
export const GetScheduledMaintenanceRequest$outboundSchema: z.ZodType<
  GetScheduledMaintenanceRequest$Outbound,
  z.ZodTypeDef,
  GetScheduledMaintenanceRequest
> = z.object({
  scheduledMaintenanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    scheduledMaintenanceId: "scheduled_maintenance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetScheduledMaintenanceRequest$ {
  /** @deprecated use `GetScheduledMaintenanceRequest$inboundSchema` instead. */
  export const inboundSchema = GetScheduledMaintenanceRequest$inboundSchema;
  /** @deprecated use `GetScheduledMaintenanceRequest$outboundSchema` instead. */
  export const outboundSchema = GetScheduledMaintenanceRequest$outboundSchema;
  /** @deprecated use `GetScheduledMaintenanceRequest$Outbound` instead. */
  export type Outbound = GetScheduledMaintenanceRequest$Outbound;
}

export function getScheduledMaintenanceRequestToJSON(
  getScheduledMaintenanceRequest: GetScheduledMaintenanceRequest,
): string {
  return JSON.stringify(
    GetScheduledMaintenanceRequest$outboundSchema.parse(
      getScheduledMaintenanceRequest,
    ),
  );
}

export function getScheduledMaintenanceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetScheduledMaintenanceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetScheduledMaintenanceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetScheduledMaintenanceRequest' from JSON`,
  );
}
