/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSignalsIngestUrlRequest = {
  /**
   * Team ID to send signals to directly
   */
  teamId?: string | null | undefined;
  /**
   * Escalation policy ID to send signals to directly. `team_id` is required if this is provided.
   */
  escalationPolicyId?: string | null | undefined;
  /**
   * On-call schedule ID to send signals to directly. `team_id` is required if this is provided.
   */
  onCallScheduleId?: string | null | undefined;
  /**
   * User ID to send signals to directly
   */
  userId?: string | null | undefined;
};

/** @internal */
export const GetSignalsIngestUrlRequest$inboundSchema: z.ZodType<
  GetSignalsIngestUrlRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  team_id: z.nullable(z.string()).optional(),
  escalation_policy_id: z.nullable(z.string()).optional(),
  on_call_schedule_id: z.nullable(z.string()).optional(),
  user_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "team_id": "teamId",
    "escalation_policy_id": "escalationPolicyId",
    "on_call_schedule_id": "onCallScheduleId",
    "user_id": "userId",
  });
});

/** @internal */
export type GetSignalsIngestUrlRequest$Outbound = {
  team_id?: string | null | undefined;
  escalation_policy_id?: string | null | undefined;
  on_call_schedule_id?: string | null | undefined;
  user_id?: string | null | undefined;
};

/** @internal */
export const GetSignalsIngestUrlRequest$outboundSchema: z.ZodType<
  GetSignalsIngestUrlRequest$Outbound,
  z.ZodTypeDef,
  GetSignalsIngestUrlRequest
> = z.object({
  teamId: z.nullable(z.string()).optional(),
  escalationPolicyId: z.nullable(z.string()).optional(),
  onCallScheduleId: z.nullable(z.string()).optional(),
  userId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    teamId: "team_id",
    escalationPolicyId: "escalation_policy_id",
    onCallScheduleId: "on_call_schedule_id",
    userId: "user_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSignalsIngestUrlRequest$ {
  /** @deprecated use `GetSignalsIngestUrlRequest$inboundSchema` instead. */
  export const inboundSchema = GetSignalsIngestUrlRequest$inboundSchema;
  /** @deprecated use `GetSignalsIngestUrlRequest$outboundSchema` instead. */
  export const outboundSchema = GetSignalsIngestUrlRequest$outboundSchema;
  /** @deprecated use `GetSignalsIngestUrlRequest$Outbound` instead. */
  export type Outbound = GetSignalsIngestUrlRequest$Outbound;
}

export function getSignalsIngestUrlRequestToJSON(
  getSignalsIngestUrlRequest: GetSignalsIngestUrlRequest,
): string {
  return JSON.stringify(
    GetSignalsIngestUrlRequest$outboundSchema.parse(getSignalsIngestUrlRequest),
  );
}

export function getSignalsIngestUrlRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSignalsIngestUrlRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSignalsIngestUrlRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSignalsIngestUrlRequest' from JSON`,
  );
}
