/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTeamSignalRuleRequest = {
  teamId: string;
  id: string;
};

/** @internal */
export const GetTeamSignalRuleRequest$inboundSchema: z.ZodType<
  GetTeamSignalRuleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  team_id: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "team_id": "teamId",
  });
});
/** @internal */
export type GetTeamSignalRuleRequest$Outbound = {
  team_id: string;
  id: string;
};

/** @internal */
export const GetTeamSignalRuleRequest$outboundSchema: z.ZodType<
  GetTeamSignalRuleRequest$Outbound,
  z.ZodTypeDef,
  GetTeamSignalRuleRequest
> = z.object({
  teamId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    teamId: "team_id",
  });
});

export function getTeamSignalRuleRequestToJSON(
  getTeamSignalRuleRequest: GetTeamSignalRuleRequest,
): string {
  return JSON.stringify(
    GetTeamSignalRuleRequest$outboundSchema.parse(getTeamSignalRuleRequest),
  );
}
export function getTeamSignalRuleRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTeamSignalRuleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTeamSignalRuleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTeamSignalRuleRequest' from JSON`,
  );
}
