/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListSeverityMatrixConditionsRequest = {
  page?: number | null | undefined;
  perPage?: number | null | undefined;
};

/** @internal */
export const ListSeverityMatrixConditionsRequest$inboundSchema: z.ZodType<
  ListSeverityMatrixConditionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  per_page: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "per_page": "perPage",
  });
});

/** @internal */
export type ListSeverityMatrixConditionsRequest$Outbound = {
  page?: number | null | undefined;
  per_page?: number | null | undefined;
};

/** @internal */
export const ListSeverityMatrixConditionsRequest$outboundSchema: z.ZodType<
  ListSeverityMatrixConditionsRequest$Outbound,
  z.ZodTypeDef,
  ListSeverityMatrixConditionsRequest
> = z.object({
  page: z.nullable(z.number().int()).optional(),
  perPage: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    perPage: "per_page",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListSeverityMatrixConditionsRequest$ {
  /** @deprecated use `ListSeverityMatrixConditionsRequest$inboundSchema` instead. */
  export const inboundSchema =
    ListSeverityMatrixConditionsRequest$inboundSchema;
  /** @deprecated use `ListSeverityMatrixConditionsRequest$outboundSchema` instead. */
  export const outboundSchema =
    ListSeverityMatrixConditionsRequest$outboundSchema;
  /** @deprecated use `ListSeverityMatrixConditionsRequest$Outbound` instead. */
  export type Outbound = ListSeverityMatrixConditionsRequest$Outbound;
}

export function listSeverityMatrixConditionsRequestToJSON(
  listSeverityMatrixConditionsRequest: ListSeverityMatrixConditionsRequest,
): string {
  return JSON.stringify(
    ListSeverityMatrixConditionsRequest$outboundSchema.parse(
      listSeverityMatrixConditionsRequest,
    ),
  );
}

export function listSeverityMatrixConditionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListSeverityMatrixConditionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListSeverityMatrixConditionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSeverityMatrixConditionsRequest' from JSON`,
  );
}
