/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PreviewOnCallScheduleRotationRequest = {
  teamId: string;
  scheduleId: string;
  previewOnCallScheduleRotation: components.PreviewOnCallScheduleRotation;
};

/** @internal */
export const PreviewOnCallScheduleRotationRequest$inboundSchema: z.ZodType<
  PreviewOnCallScheduleRotationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  team_id: z.string(),
  schedule_id: z.string(),
  preview_on_call_schedule_rotation: z.lazy(() =>
    components.PreviewOnCallScheduleRotation$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "team_id": "teamId",
    "schedule_id": "scheduleId",
    "preview_on_call_schedule_rotation": "previewOnCallScheduleRotation",
  });
});

/** @internal */
export type PreviewOnCallScheduleRotationRequest$Outbound = {
  team_id: string;
  schedule_id: string;
  preview_on_call_schedule_rotation:
    components.PreviewOnCallScheduleRotation$Outbound;
};

/** @internal */
export const PreviewOnCallScheduleRotationRequest$outboundSchema: z.ZodType<
  PreviewOnCallScheduleRotationRequest$Outbound,
  z.ZodTypeDef,
  PreviewOnCallScheduleRotationRequest
> = z.object({
  teamId: z.string(),
  scheduleId: z.string(),
  previewOnCallScheduleRotation: z.lazy(() =>
    components.PreviewOnCallScheduleRotation$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    teamId: "team_id",
    scheduleId: "schedule_id",
    previewOnCallScheduleRotation: "preview_on_call_schedule_rotation",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreviewOnCallScheduleRotationRequest$ {
  /** @deprecated use `PreviewOnCallScheduleRotationRequest$inboundSchema` instead. */
  export const inboundSchema =
    PreviewOnCallScheduleRotationRequest$inboundSchema;
  /** @deprecated use `PreviewOnCallScheduleRotationRequest$outboundSchema` instead. */
  export const outboundSchema =
    PreviewOnCallScheduleRotationRequest$outboundSchema;
  /** @deprecated use `PreviewOnCallScheduleRotationRequest$Outbound` instead. */
  export type Outbound = PreviewOnCallScheduleRotationRequest$Outbound;
}

export function previewOnCallScheduleRotationRequestToJSON(
  previewOnCallScheduleRotationRequest: PreviewOnCallScheduleRotationRequest,
): string {
  return JSON.stringify(
    PreviewOnCallScheduleRotationRequest$outboundSchema.parse(
      previewOnCallScheduleRotationRequest,
    ),
  );
}

export function previewOnCallScheduleRotationRequestFromJSON(
  jsonString: string,
): SafeParseResult<PreviewOnCallScheduleRotationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PreviewOnCallScheduleRotationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewOnCallScheduleRotationRequest' from JSON`,
  );
}
