/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PublishNuncConnectionRequest = {
  nuncConnectionId: string;
};

/** @internal */
export const PublishNuncConnectionRequest$inboundSchema: z.ZodType<
  PublishNuncConnectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  nunc_connection_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "nunc_connection_id": "nuncConnectionId",
  });
});
/** @internal */
export type PublishNuncConnectionRequest$Outbound = {
  nunc_connection_id: string;
};

/** @internal */
export const PublishNuncConnectionRequest$outboundSchema: z.ZodType<
  PublishNuncConnectionRequest$Outbound,
  z.ZodTypeDef,
  PublishNuncConnectionRequest
> = z.object({
  nuncConnectionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    nuncConnectionId: "nunc_connection_id",
  });
});

export function publishNuncConnectionRequestToJSON(
  publishNuncConnectionRequest: PublishNuncConnectionRequest,
): string {
  return JSON.stringify(
    PublishNuncConnectionRequest$outboundSchema.parse(
      publishNuncConnectionRequest,
    ),
  );
}
export function publishNuncConnectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PublishNuncConnectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublishNuncConnectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublishNuncConnectionRequest' from JSON`,
  );
}
