/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnarchiveIncidentRequest = {
  incidentId: string;
};

/** @internal */
export const UnarchiveIncidentRequest$inboundSchema: z.ZodType<
  UnarchiveIncidentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
  });
});

/** @internal */
export type UnarchiveIncidentRequest$Outbound = {
  incident_id: string;
};

/** @internal */
export const UnarchiveIncidentRequest$outboundSchema: z.ZodType<
  UnarchiveIncidentRequest$Outbound,
  z.ZodTypeDef,
  UnarchiveIncidentRequest
> = z.object({
  incidentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnarchiveIncidentRequest$ {
  /** @deprecated use `UnarchiveIncidentRequest$inboundSchema` instead. */
  export const inboundSchema = UnarchiveIncidentRequest$inboundSchema;
  /** @deprecated use `UnarchiveIncidentRequest$outboundSchema` instead. */
  export const outboundSchema = UnarchiveIncidentRequest$outboundSchema;
  /** @deprecated use `UnarchiveIncidentRequest$Outbound` instead. */
  export type Outbound = UnarchiveIncidentRequest$Outbound;
}

export function unarchiveIncidentRequestToJSON(
  unarchiveIncidentRequest: UnarchiveIncidentRequest,
): string {
  return JSON.stringify(
    UnarchiveIncidentRequest$outboundSchema.parse(unarchiveIncidentRequest),
  );
}

export function unarchiveIncidentRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnarchiveIncidentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnarchiveIncidentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnarchiveIncidentRequest' from JSON`,
  );
}
