/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateSavedSearchResourceType = {
  ChangeEvents: "change_events",
  Incidents: "incidents",
  Services: "services",
  ScheduledMaintenances: "scheduled_maintenances",
  TicketTasks: "ticket_tasks",
  TicketFollowUps: "ticket_follow_ups",
  Analytics: "analytics",
  ImpactAnalytics: "impact_analytics",
  Alerts: "alerts",
  AlertAnalytics: "alert_analytics",
  IncidentEvents: "incident_events",
} as const;
export type UpdateSavedSearchResourceType = ClosedEnum<
  typeof UpdateSavedSearchResourceType
>;

export type UpdateSavedSearchRequest = {
  resourceType: UpdateSavedSearchResourceType;
  savedSearchId: string;
  updateSavedSearch: components.UpdateSavedSearch;
};

/** @internal */
export const UpdateSavedSearchResourceType$inboundSchema: z.ZodNativeEnum<
  typeof UpdateSavedSearchResourceType
> = z.nativeEnum(UpdateSavedSearchResourceType);
/** @internal */
export const UpdateSavedSearchResourceType$outboundSchema: z.ZodNativeEnum<
  typeof UpdateSavedSearchResourceType
> = UpdateSavedSearchResourceType$inboundSchema;

/** @internal */
export const UpdateSavedSearchRequest$inboundSchema: z.ZodType<
  UpdateSavedSearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: UpdateSavedSearchResourceType$inboundSchema,
  saved_search_id: z.string(),
  update_saved_search: z.lazy(() => components.UpdateSavedSearch$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "saved_search_id": "savedSearchId",
    "update_saved_search": "updateSavedSearch",
  });
});
/** @internal */
export type UpdateSavedSearchRequest$Outbound = {
  resource_type: string;
  saved_search_id: string;
  update_saved_search: components.UpdateSavedSearch$Outbound;
};

/** @internal */
export const UpdateSavedSearchRequest$outboundSchema: z.ZodType<
  UpdateSavedSearchRequest$Outbound,
  z.ZodTypeDef,
  UpdateSavedSearchRequest
> = z.object({
  resourceType: UpdateSavedSearchResourceType$outboundSchema,
  savedSearchId: z.string(),
  updateSavedSearch: z.lazy(() => components.UpdateSavedSearch$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    savedSearchId: "saved_search_id",
    updateSavedSearch: "update_saved_search",
  });
});

export function updateSavedSearchRequestToJSON(
  updateSavedSearchRequest: UpdateSavedSearchRequest,
): string {
  return JSON.stringify(
    UpdateSavedSearchRequest$outboundSchema.parse(updateSavedSearchRequest),
  );
}
export function updateSavedSearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSavedSearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSavedSearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSavedSearchRequest' from JSON`,
  );
}
