/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateSeverityMatrixImpactRequest = {
  impactId: string;
  patchV1SeverityMatrixImpactsImpactId:
    components.PatchV1SeverityMatrixImpactsImpactId;
};

/** @internal */
export const UpdateSeverityMatrixImpactRequest$inboundSchema: z.ZodType<
  UpdateSeverityMatrixImpactRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  impact_id: z.string(),
  patchV1SeverityMatrixImpactsImpactId:
    components.PatchV1SeverityMatrixImpactsImpactId$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "impact_id": "impactId",
  });
});

/** @internal */
export type UpdateSeverityMatrixImpactRequest$Outbound = {
  impact_id: string;
  patchV1SeverityMatrixImpactsImpactId:
    components.PatchV1SeverityMatrixImpactsImpactId$Outbound;
};

/** @internal */
export const UpdateSeverityMatrixImpactRequest$outboundSchema: z.ZodType<
  UpdateSeverityMatrixImpactRequest$Outbound,
  z.ZodTypeDef,
  UpdateSeverityMatrixImpactRequest
> = z.object({
  impactId: z.string(),
  patchV1SeverityMatrixImpactsImpactId:
    components.PatchV1SeverityMatrixImpactsImpactId$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    impactId: "impact_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSeverityMatrixImpactRequest$ {
  /** @deprecated use `UpdateSeverityMatrixImpactRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateSeverityMatrixImpactRequest$inboundSchema;
  /** @deprecated use `UpdateSeverityMatrixImpactRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateSeverityMatrixImpactRequest$outboundSchema;
  /** @deprecated use `UpdateSeverityMatrixImpactRequest$Outbound` instead. */
  export type Outbound = UpdateSeverityMatrixImpactRequest$Outbound;
}

export function updateSeverityMatrixImpactRequestToJSON(
  updateSeverityMatrixImpactRequest: UpdateSeverityMatrixImpactRequest,
): string {
  return JSON.stringify(
    UpdateSeverityMatrixImpactRequest$outboundSchema.parse(
      updateSeverityMatrixImpactRequest,
    ),
  );
}

export function updateSeverityMatrixImpactRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSeverityMatrixImpactRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSeverityMatrixImpactRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSeverityMatrixImpactRequest' from JSON`,
  );
}
