/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAiPreferencesRequest = {
  /**
   * Whether to enable AI features
   */
  ai?: boolean | null | undefined;
  /**
   * Whether to enable incident summaries
   */
  summaries?: boolean | null | undefined;
  /**
   * Whether to enable incident descriptions
   */
  description?: boolean | null | undefined;
  /**
   * Whether to enable incident impact
   */
  impact?: boolean | null | undefined;
  /**
   * Whether to enable incident updates
   */
  updates?: boolean | null | undefined;
  /**
   * Whether to enable incident retrospectives
   */
  retros?: boolean | null | undefined;
  /**
   * Whether to enable incident followups
   */
  followups?: boolean | null | undefined;
  /**
   * Whether to enable similar incidents
   */
  similarIncidents?: boolean | null | undefined;
  /**
   * Minimum minutes between related-incident posts per incident. 0 disables the cooldown. Null = no cooldown.
   */
  similarIncidentsCooldownMinutes?: number | null | undefined;
  /**
   * Maximum related-incident posts per incident lifetime. 0 disables related-incident posts entirely. Null = no cap.
   */
  similarIncidentsMaxPerIncident?: number | null | undefined;
  /**
   * Minimum minutes between conference bridge summary posts. Null uses the default (5 minutes).
   */
  conferenceBridgeSummaryMinIntervalMinutes?: number | null | undefined;
};

/** @internal */
export const UpdateAiPreferencesRequest$inboundSchema: z.ZodType<
  UpdateAiPreferencesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ai: z.nullable(z.boolean()).optional(),
  summaries: z.nullable(z.boolean()).optional(),
  description: z.nullable(z.boolean()).optional(),
  impact: z.nullable(z.boolean()).optional(),
  updates: z.nullable(z.boolean()).optional(),
  retros: z.nullable(z.boolean()).optional(),
  followups: z.nullable(z.boolean()).optional(),
  similar_incidents: z.nullable(z.boolean()).optional(),
  similar_incidents_cooldown_minutes: z.nullable(z.number().int()).optional(),
  similar_incidents_max_per_incident: z.nullable(z.number().int()).optional(),
  conference_bridge_summary_min_interval_minutes: z.nullable(z.number().int())
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "similar_incidents": "similarIncidents",
    "similar_incidents_cooldown_minutes": "similarIncidentsCooldownMinutes",
    "similar_incidents_max_per_incident": "similarIncidentsMaxPerIncident",
    "conference_bridge_summary_min_interval_minutes":
      "conferenceBridgeSummaryMinIntervalMinutes",
  });
});
/** @internal */
export type UpdateAiPreferencesRequest$Outbound = {
  ai?: boolean | null | undefined;
  summaries?: boolean | null | undefined;
  description?: boolean | null | undefined;
  impact?: boolean | null | undefined;
  updates?: boolean | null | undefined;
  retros?: boolean | null | undefined;
  followups?: boolean | null | undefined;
  similar_incidents?: boolean | null | undefined;
  similar_incidents_cooldown_minutes?: number | null | undefined;
  similar_incidents_max_per_incident?: number | null | undefined;
  conference_bridge_summary_min_interval_minutes?: number | null | undefined;
};

/** @internal */
export const UpdateAiPreferencesRequest$outboundSchema: z.ZodType<
  UpdateAiPreferencesRequest$Outbound,
  z.ZodTypeDef,
  UpdateAiPreferencesRequest
> = z.object({
  ai: z.nullable(z.boolean()).optional(),
  summaries: z.nullable(z.boolean()).optional(),
  description: z.nullable(z.boolean()).optional(),
  impact: z.nullable(z.boolean()).optional(),
  updates: z.nullable(z.boolean()).optional(),
  retros: z.nullable(z.boolean()).optional(),
  followups: z.nullable(z.boolean()).optional(),
  similarIncidents: z.nullable(z.boolean()).optional(),
  similarIncidentsCooldownMinutes: z.nullable(z.number().int()).optional(),
  similarIncidentsMaxPerIncident: z.nullable(z.number().int()).optional(),
  conferenceBridgeSummaryMinIntervalMinutes: z.nullable(z.number().int())
    .optional(),
}).transform((v) => {
  return remap$(v, {
    similarIncidents: "similar_incidents",
    similarIncidentsCooldownMinutes: "similar_incidents_cooldown_minutes",
    similarIncidentsMaxPerIncident: "similar_incidents_max_per_incident",
    conferenceBridgeSummaryMinIntervalMinutes:
      "conference_bridge_summary_min_interval_minutes",
  });
});

export function updateAiPreferencesRequestToJSON(
  updateAiPreferencesRequest: UpdateAiPreferencesRequest,
): string {
  return JSON.stringify(
    UpdateAiPreferencesRequest$outboundSchema.parse(updateAiPreferencesRequest),
  );
}
export function updateAiPreferencesRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAiPreferencesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAiPreferencesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAiPreferencesRequest' from JSON`,
  );
}
