/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateFieldMapRequest = {
  fieldMapId: string;
};

/** @internal */
export const UpdateFieldMapRequest$inboundSchema: z.ZodType<
  UpdateFieldMapRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  field_map_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "field_map_id": "fieldMapId",
  });
});
/** @internal */
export type UpdateFieldMapRequest$Outbound = {
  field_map_id: string;
};

/** @internal */
export const UpdateFieldMapRequest$outboundSchema: z.ZodType<
  UpdateFieldMapRequest$Outbound,
  z.ZodTypeDef,
  UpdateFieldMapRequest
> = z.object({
  fieldMapId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fieldMapId: "field_map_id",
  });
});

export function updateFieldMapRequestToJSON(
  updateFieldMapRequest: UpdateFieldMapRequest,
): string {
  return JSON.stringify(
    UpdateFieldMapRequest$outboundSchema.parse(updateFieldMapRequest),
  );
}
export function updateFieldMapRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFieldMapRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateFieldMapRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFieldMapRequest' from JSON`,
  );
}
