/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateScimUserRequest = {
  id: string;
  updateScimUser: components.UpdateScimUser;
};

/** @internal */
export const UpdateScimUserRequest$inboundSchema: z.ZodType<
  UpdateScimUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  update_scim_user: z.lazy(() => components.UpdateScimUser$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "update_scim_user": "updateScimUser",
  });
});

/** @internal */
export type UpdateScimUserRequest$Outbound = {
  id: string;
  update_scim_user: components.UpdateScimUser$Outbound;
};

/** @internal */
export const UpdateScimUserRequest$outboundSchema: z.ZodType<
  UpdateScimUserRequest$Outbound,
  z.ZodTypeDef,
  UpdateScimUserRequest
> = z.object({
  id: z.string(),
  updateScimUser: z.lazy(() => components.UpdateScimUser$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    updateScimUser: "update_scim_user",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateScimUserRequest$ {
  /** @deprecated use `UpdateScimUserRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateScimUserRequest$inboundSchema;
  /** @deprecated use `UpdateScimUserRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateScimUserRequest$outboundSchema;
  /** @deprecated use `UpdateScimUserRequest$Outbound` instead. */
  export type Outbound = UpdateScimUserRequest$Outbound;
}

export function updateScimUserRequestToJSON(
  updateScimUserRequest: UpdateScimUserRequest,
): string {
  return JSON.stringify(
    UpdateScimUserRequest$outboundSchema.parse(updateScimUserRequest),
  );
}

export function updateScimUserRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScimUserRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScimUserRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScimUserRequest' from JSON`,
  );
}
