/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConversationsAPIEntitiesChannel = {
  name?: string | undefined;
};

/** @internal */
export const ConversationsAPIEntitiesChannel$inboundSchema: z.ZodType<
  ConversationsAPIEntitiesChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
});

/** @internal */
export type ConversationsAPIEntitiesChannel$Outbound = {
  name?: string | undefined;
};

/** @internal */
export const ConversationsAPIEntitiesChannel$outboundSchema: z.ZodType<
  ConversationsAPIEntitiesChannel$Outbound,
  z.ZodTypeDef,
  ConversationsAPIEntitiesChannel
> = z.object({
  name: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConversationsAPIEntitiesChannel$ {
  /** @deprecated use `ConversationsAPIEntitiesChannel$inboundSchema` instead. */
  export const inboundSchema = ConversationsAPIEntitiesChannel$inboundSchema;
  /** @deprecated use `ConversationsAPIEntitiesChannel$outboundSchema` instead. */
  export const outboundSchema = ConversationsAPIEntitiesChannel$outboundSchema;
  /** @deprecated use `ConversationsAPIEntitiesChannel$Outbound` instead. */
  export type Outbound = ConversationsAPIEntitiesChannel$Outbound;
}

export function conversationsAPIEntitiesChannelToJSON(
  conversationsAPIEntitiesChannel: ConversationsAPIEntitiesChannel,
): string {
  return JSON.stringify(
    ConversationsAPIEntitiesChannel$outboundSchema.parse(
      conversationsAPIEntitiesChannel,
    ),
  );
}

export function conversationsAPIEntitiesChannelFromJSON(
  jsonString: string,
): SafeParseResult<ConversationsAPIEntitiesChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationsAPIEntitiesChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationsAPIEntitiesChannel' from JSON`,
  );
}
