/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Creates a ticket for a project
 */
export type CreateTicket = {
  summary: string;
  /**
   * Which incident this ticket is related to, in the format of 'incident/UUID'
   */
  relatedTo?: string | null | undefined;
  projectId?: string | null | undefined;
  description?: string | null | undefined;
  state?: string | null | undefined;
  type?: string | null | undefined;
  priorityId?: string | null | undefined;
  /**
   * List of tags for the ticket
   */
  tagList?: Array<string> | null | undefined;
  /**
   * The remote URL for an existing ticket in a supported and configured ticketing integration
   */
  remoteUrl?: string | null | undefined;
};

/** @internal */
export const CreateTicket$inboundSchema: z.ZodType<
  CreateTicket,
  z.ZodTypeDef,
  unknown
> = z.object({
  summary: z.string(),
  related_to: z.nullable(z.string()).optional(),
  project_id: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  priority_id: z.nullable(z.string()).optional(),
  tag_list: z.nullable(z.array(z.string())).optional(),
  remote_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "related_to": "relatedTo",
    "project_id": "projectId",
    "priority_id": "priorityId",
    "tag_list": "tagList",
    "remote_url": "remoteUrl",
  });
});

/** @internal */
export type CreateTicket$Outbound = {
  summary: string;
  related_to?: string | null | undefined;
  project_id?: string | null | undefined;
  description?: string | null | undefined;
  state?: string | null | undefined;
  type?: string | null | undefined;
  priority_id?: string | null | undefined;
  tag_list?: Array<string> | null | undefined;
  remote_url?: string | null | undefined;
};

/** @internal */
export const CreateTicket$outboundSchema: z.ZodType<
  CreateTicket$Outbound,
  z.ZodTypeDef,
  CreateTicket
> = z.object({
  summary: z.string(),
  relatedTo: z.nullable(z.string()).optional(),
  projectId: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  priorityId: z.nullable(z.string()).optional(),
  tagList: z.nullable(z.array(z.string())).optional(),
  remoteUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    relatedTo: "related_to",
    projectId: "project_id",
    priorityId: "priority_id",
    tagList: "tag_list",
    remoteUrl: "remote_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTicket$ {
  /** @deprecated use `CreateTicket$inboundSchema` instead. */
  export const inboundSchema = CreateTicket$inboundSchema;
  /** @deprecated use `CreateTicket$outboundSchema` instead. */
  export const outboundSchema = CreateTicket$outboundSchema;
  /** @deprecated use `CreateTicket$Outbound` instead. */
  export type Outbound = CreateTicket$Outbound;
}

export function createTicketToJSON(createTicket: CreateTicket): string {
  return JSON.stringify(CreateTicket$outboundSchema.parse(createTicket));
}

export function createTicketFromJSON(
  jsonString: string,
): SafeParseResult<CreateTicket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTicket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTicket' from JSON`,
  );
}
