/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ServiceEntity,
  ServiceEntity$inboundSchema,
  ServiceEntity$Outbound,
  ServiceEntity$outboundSchema,
} from "./serviceentity.js";

/**
 * FunctionalityWithAllServicesEntity model
 */
export type FunctionalityWithAllServicesEntity = {
  /**
   * Services this functionality provides
   */
  services?: Array<ServiceEntity> | null | undefined;
};

/** @internal */
export const FunctionalityWithAllServicesEntity$inboundSchema: z.ZodType<
  FunctionalityWithAllServicesEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  services: z.nullable(z.array(ServiceEntity$inboundSchema)).optional(),
});
/** @internal */
export type FunctionalityWithAllServicesEntity$Outbound = {
  services?: Array<ServiceEntity$Outbound> | null | undefined;
};

/** @internal */
export const FunctionalityWithAllServicesEntity$outboundSchema: z.ZodType<
  FunctionalityWithAllServicesEntity$Outbound,
  z.ZodTypeDef,
  FunctionalityWithAllServicesEntity
> = z.object({
  services: z.nullable(z.array(ServiceEntity$outboundSchema)).optional(),
});

export function functionalityWithAllServicesEntityToJSON(
  functionalityWithAllServicesEntity: FunctionalityWithAllServicesEntity,
): string {
  return JSON.stringify(
    FunctionalityWithAllServicesEntity$outboundSchema.parse(
      functionalityWithAllServicesEntity,
    ),
  );
}
export function functionalityWithAllServicesEntityFromJSON(
  jsonString: string,
): SafeParseResult<FunctionalityWithAllServicesEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FunctionalityWithAllServicesEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionalityWithAllServicesEntity' from JSON`,
  );
}
