/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Incidents_ChannelEntity model
 */
export type IncidentsChannelEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  source?: string | null | undefined;
  sourceName?: string | null | undefined;
  sourceId?: string | null | undefined;
  url?: string | null | undefined;
  iconUrl?: string | null | undefined;
  status?: string | null | undefined;
};

/** @internal */
export const IncidentsChannelEntity$inboundSchema: z.ZodType<
  IncidentsChannelEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  source: z.nullable(z.string()).optional(),
  source_name: z.nullable(z.string()).optional(),
  source_id: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  icon_url: z.nullable(z.string()).optional(),
  status: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "source_name": "sourceName",
    "source_id": "sourceId",
    "icon_url": "iconUrl",
  });
});
/** @internal */
export type IncidentsChannelEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  source?: string | null | undefined;
  source_name?: string | null | undefined;
  source_id?: string | null | undefined;
  url?: string | null | undefined;
  icon_url?: string | null | undefined;
  status?: string | null | undefined;
};

/** @internal */
export const IncidentsChannelEntity$outboundSchema: z.ZodType<
  IncidentsChannelEntity$Outbound,
  z.ZodTypeDef,
  IncidentsChannelEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  source: z.nullable(z.string()).optional(),
  sourceName: z.nullable(z.string()).optional(),
  sourceId: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  iconUrl: z.nullable(z.string()).optional(),
  status: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    sourceName: "source_name",
    sourceId: "source_id",
    iconUrl: "icon_url",
  });
});

export function incidentsChannelEntityToJSON(
  incidentsChannelEntity: IncidentsChannelEntity,
): string {
  return JSON.stringify(
    IncidentsChannelEntity$outboundSchema.parse(incidentsChannelEntity),
  );
}
export function incidentsChannelEntityFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsChannelEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentsChannelEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsChannelEntity' from JSON`,
  );
}
