/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$inboundSchema,
  NullableAuthorEntity$Outbound,
  NullableAuthorEntity$outboundSchema,
} from "./nullableauthorentity.js";

export type IncidentsLifecycleMilestoneEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  position?: number | null | undefined;
  occurredAt?: Date | null | undefined;
  duration?: string | null | undefined;
  updatedBy?: NullableAuthorEntity | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const IncidentsLifecycleMilestoneEntity$inboundSchema: z.ZodType<
  IncidentsLifecycleMilestoneEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
  occurred_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  duration: z.nullable(z.string()).optional(),
  updated_by: z.nullable(NullableAuthorEntity$inboundSchema).optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "occurred_at": "occurredAt",
    "updated_by": "updatedBy",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type IncidentsLifecycleMilestoneEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  slug?: string | null | undefined;
  position?: number | null | undefined;
  occurred_at?: string | null | undefined;
  duration?: string | null | undefined;
  updated_by?: NullableAuthorEntity$Outbound | null | undefined;
  updated_at?: string | null | undefined;
};

/** @internal */
export const IncidentsLifecycleMilestoneEntity$outboundSchema: z.ZodType<
  IncidentsLifecycleMilestoneEntity$Outbound,
  z.ZodTypeDef,
  IncidentsLifecycleMilestoneEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
  occurredAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  duration: z.nullable(z.string()).optional(),
  updatedBy: z.nullable(NullableAuthorEntity$outboundSchema).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    occurredAt: "occurred_at",
    updatedBy: "updated_by",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentsLifecycleMilestoneEntity$ {
  /** @deprecated use `IncidentsLifecycleMilestoneEntity$inboundSchema` instead. */
  export const inboundSchema = IncidentsLifecycleMilestoneEntity$inboundSchema;
  /** @deprecated use `IncidentsLifecycleMilestoneEntity$outboundSchema` instead. */
  export const outboundSchema =
    IncidentsLifecycleMilestoneEntity$outboundSchema;
  /** @deprecated use `IncidentsLifecycleMilestoneEntity$Outbound` instead. */
  export type Outbound = IncidentsLifecycleMilestoneEntity$Outbound;
}

export function incidentsLifecycleMilestoneEntityToJSON(
  incidentsLifecycleMilestoneEntity: IncidentsLifecycleMilestoneEntity,
): string {
  return JSON.stringify(
    IncidentsLifecycleMilestoneEntity$outboundSchema.parse(
      incidentsLifecycleMilestoneEntity,
    ),
  );
}

export function incidentsLifecycleMilestoneEntityFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsLifecycleMilestoneEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentsLifecycleMilestoneEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsLifecycleMilestoneEntity' from JSON`,
  );
}
