/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuthorEntity,
  AuthorEntity$inboundSchema,
  AuthorEntity$Outbound,
  AuthorEntity$outboundSchema,
} from "./authorentity.js";
import {
  ConversationsAPIEntitiesReference,
  ConversationsAPIEntitiesReference$inboundSchema,
  ConversationsAPIEntitiesReference$Outbound,
  ConversationsAPIEntitiesReference$outboundSchema,
} from "./conversationsapientitiesreference.js";
import {
  VotesEntity,
  VotesEntity$inboundSchema,
  VotesEntity$Outbound,
  VotesEntity$outboundSchema,
} from "./votesentity.js";

/**
 * Can be one of: NoteEntity, TourStepEntity, RootCauseEntity, ChangeTypeEntity, RoleUpdateEntity, TaskUpdateEntity, AlertLinkedEntity, ChatMessageEntity, AddTaskListEntity, ImpactUpdateEntity, TicketUpdateEntity, GeneralUpdateEntity, ChangelogEntryEntity, IncidentStatusEntity, TeamAssignmentEntity, BulkUpdateEntity
 */
export type IncidentEventEntityData = {};

export const Visibility = {
  PrivateToOrg: "private_to_org",
  OpenToPublic: "open_to_public",
  InternalStatusPage: "internal_status_page",
} as const;
export type Visibility = ClosedEnum<typeof Visibility>;

/**
 * IncidentEventEntity model
 */
export type IncidentEventEntity = {
  id?: string | undefined;
  incidentId?: string | undefined;
  type?: string | undefined;
  context?: string | undefined;
  /**
   * Can be one of: NoteEntity, TourStepEntity, RootCauseEntity, ChangeTypeEntity, RoleUpdateEntity, TaskUpdateEntity, AlertLinkedEntity, ChatMessageEntity, AddTaskListEntity, ImpactUpdateEntity, TicketUpdateEntity, GeneralUpdateEntity, ChangelogEntryEntity, IncidentStatusEntity, TeamAssignmentEntity, BulkUpdateEntity
   */
  data?: IncidentEventEntityData | undefined;
  occurredAt?: Date | undefined;
  visibility?: Visibility | undefined;
  author?: AuthorEntity | undefined;
  /**
   * VotesEntity model
   */
  votes?: VotesEntity | undefined;
  conversations?: Array<ConversationsAPIEntitiesReference> | undefined;
};

/** @internal */
export const IncidentEventEntityData$inboundSchema: z.ZodType<
  IncidentEventEntityData,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type IncidentEventEntityData$Outbound = {};

/** @internal */
export const IncidentEventEntityData$outboundSchema: z.ZodType<
  IncidentEventEntityData$Outbound,
  z.ZodTypeDef,
  IncidentEventEntityData
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentEventEntityData$ {
  /** @deprecated use `IncidentEventEntityData$inboundSchema` instead. */
  export const inboundSchema = IncidentEventEntityData$inboundSchema;
  /** @deprecated use `IncidentEventEntityData$outboundSchema` instead. */
  export const outboundSchema = IncidentEventEntityData$outboundSchema;
  /** @deprecated use `IncidentEventEntityData$Outbound` instead. */
  export type Outbound = IncidentEventEntityData$Outbound;
}

export function incidentEventEntityDataToJSON(
  incidentEventEntityData: IncidentEventEntityData,
): string {
  return JSON.stringify(
    IncidentEventEntityData$outboundSchema.parse(incidentEventEntityData),
  );
}

export function incidentEventEntityDataFromJSON(
  jsonString: string,
): SafeParseResult<IncidentEventEntityData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentEventEntityData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentEventEntityData' from JSON`,
  );
}

/** @internal */
export const Visibility$inboundSchema: z.ZodNativeEnum<typeof Visibility> = z
  .nativeEnum(Visibility);

/** @internal */
export const Visibility$outboundSchema: z.ZodNativeEnum<typeof Visibility> =
  Visibility$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Visibility$ {
  /** @deprecated use `Visibility$inboundSchema` instead. */
  export const inboundSchema = Visibility$inboundSchema;
  /** @deprecated use `Visibility$outboundSchema` instead. */
  export const outboundSchema = Visibility$outboundSchema;
}

/** @internal */
export const IncidentEventEntity$inboundSchema: z.ZodType<
  IncidentEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  incident_id: z.string().optional(),
  type: z.string().optional(),
  context: z.string().optional(),
  data: z.lazy(() => IncidentEventEntityData$inboundSchema).optional(),
  occurred_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  visibility: Visibility$inboundSchema.optional(),
  author: AuthorEntity$inboundSchema.optional(),
  votes: VotesEntity$inboundSchema.optional(),
  conversations: z.array(ConversationsAPIEntitiesReference$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
    "occurred_at": "occurredAt",
  });
});

/** @internal */
export type IncidentEventEntity$Outbound = {
  id?: string | undefined;
  incident_id?: string | undefined;
  type?: string | undefined;
  context?: string | undefined;
  data?: IncidentEventEntityData$Outbound | undefined;
  occurred_at?: string | undefined;
  visibility?: string | undefined;
  author?: AuthorEntity$Outbound | undefined;
  votes?: VotesEntity$Outbound | undefined;
  conversations?: Array<ConversationsAPIEntitiesReference$Outbound> | undefined;
};

/** @internal */
export const IncidentEventEntity$outboundSchema: z.ZodType<
  IncidentEventEntity$Outbound,
  z.ZodTypeDef,
  IncidentEventEntity
> = z.object({
  id: z.string().optional(),
  incidentId: z.string().optional(),
  type: z.string().optional(),
  context: z.string().optional(),
  data: z.lazy(() => IncidentEventEntityData$outboundSchema).optional(),
  occurredAt: z.date().transform(v => v.toISOString()).optional(),
  visibility: Visibility$outboundSchema.optional(),
  author: AuthorEntity$outboundSchema.optional(),
  votes: VotesEntity$outboundSchema.optional(),
  conversations: z.array(ConversationsAPIEntitiesReference$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
    occurredAt: "occurred_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncidentEventEntity$ {
  /** @deprecated use `IncidentEventEntity$inboundSchema` instead. */
  export const inboundSchema = IncidentEventEntity$inboundSchema;
  /** @deprecated use `IncidentEventEntity$outboundSchema` instead. */
  export const outboundSchema = IncidentEventEntity$outboundSchema;
  /** @deprecated use `IncidentEventEntity$Outbound` instead. */
  export type Outbound = IncidentEventEntity$Outbound;
}

export function incidentEventEntityToJSON(
  incidentEventEntity: IncidentEventEntity,
): string {
  return JSON.stringify(
    IncidentEventEntity$outboundSchema.parse(incidentEventEntity),
  );
}

export function incidentEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<IncidentEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentEventEntity' from JSON`,
  );
}
