/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Encoding for submitted data
 */
export const Encoding = {
  TextYaml: "text/yaml",
  ApplicationXYaml: "application/x-yaml",
  ApplicationJson: "application/json",
} as const;
/**
 * Encoding for submitted data
 */
export type Encoding = ClosedEnum<typeof Encoding>;

/**
 * Accepts catalog data in the configured format and asyncronously processes the data to incorporate changes into service catalog.
 */
export type IngestCatalogData = {
  /**
   * Encoding for submitted data
   */
  encoding: Encoding;
  /**
   * Service data
   */
  data: string;
};

/** @internal */
export const Encoding$inboundSchema: z.ZodNativeEnum<typeof Encoding> = z
  .nativeEnum(Encoding);
/** @internal */
export const Encoding$outboundSchema: z.ZodNativeEnum<typeof Encoding> =
  Encoding$inboundSchema;

/** @internal */
export const IngestCatalogData$inboundSchema: z.ZodType<
  IngestCatalogData,
  z.ZodTypeDef,
  unknown
> = z.object({
  encoding: Encoding$inboundSchema,
  data: z.string(),
});
/** @internal */
export type IngestCatalogData$Outbound = {
  encoding: string;
  data: string;
};

/** @internal */
export const IngestCatalogData$outboundSchema: z.ZodType<
  IngestCatalogData$Outbound,
  z.ZodTypeDef,
  IngestCatalogData
> = z.object({
  encoding: Encoding$outboundSchema,
  data: z.string(),
});

export function ingestCatalogDataToJSON(
  ingestCatalogData: IngestCatalogData,
): string {
  return JSON.stringify(
    IngestCatalogData$outboundSchema.parse(ingestCatalogData),
  );
}
export function ingestCatalogDataFromJSON(
  jsonString: string,
): SafeParseResult<IngestCatalogData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestCatalogData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestCatalogData' from JSON`,
  );
}
