/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IntegrationsIntegrationEntity,
  IntegrationsIntegrationEntity$inboundSchema,
  IntegrationsIntegrationEntity$Outbound,
  IntegrationsIntegrationEntity$outboundSchema,
} from "./integrationsintegrationentity.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$inboundSchema,
  NullablePaginationEntity$Outbound,
  NullablePaginationEntity$outboundSchema,
} from "./nullablepaginationentity.js";

/**
 * Integrations_IntegrationEntityPaginated model
 */
export type IntegrationsIntegrationEntityPaginated = {
  data?: Array<IntegrationsIntegrationEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

/** @internal */
export const IntegrationsIntegrationEntityPaginated$inboundSchema: z.ZodType<
  IntegrationsIntegrationEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.nullable(z.array(IntegrationsIntegrationEntity$inboundSchema))
    .optional(),
  pagination: z.nullable(NullablePaginationEntity$inboundSchema).optional(),
});

/** @internal */
export type IntegrationsIntegrationEntityPaginated$Outbound = {
  data?: Array<IntegrationsIntegrationEntity$Outbound> | null | undefined;
  pagination?: NullablePaginationEntity$Outbound | null | undefined;
};

/** @internal */
export const IntegrationsIntegrationEntityPaginated$outboundSchema: z.ZodType<
  IntegrationsIntegrationEntityPaginated$Outbound,
  z.ZodTypeDef,
  IntegrationsIntegrationEntityPaginated
> = z.object({
  data: z.nullable(z.array(IntegrationsIntegrationEntity$outboundSchema))
    .optional(),
  pagination: z.nullable(NullablePaginationEntity$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IntegrationsIntegrationEntityPaginated$ {
  /** @deprecated use `IntegrationsIntegrationEntityPaginated$inboundSchema` instead. */
  export const inboundSchema =
    IntegrationsIntegrationEntityPaginated$inboundSchema;
  /** @deprecated use `IntegrationsIntegrationEntityPaginated$outboundSchema` instead. */
  export const outboundSchema =
    IntegrationsIntegrationEntityPaginated$outboundSchema;
  /** @deprecated use `IntegrationsIntegrationEntityPaginated$Outbound` instead. */
  export type Outbound = IntegrationsIntegrationEntityPaginated$Outbound;
}

export function integrationsIntegrationEntityPaginatedToJSON(
  integrationsIntegrationEntityPaginated:
    IntegrationsIntegrationEntityPaginated,
): string {
  return JSON.stringify(
    IntegrationsIntegrationEntityPaginated$outboundSchema.parse(
      integrationsIntegrationEntityPaginated,
    ),
  );
}

export function integrationsIntegrationEntityPaginatedFromJSON(
  jsonString: string,
): SafeParseResult<IntegrationsIntegrationEntityPaginated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IntegrationsIntegrationEntityPaginated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntegrationsIntegrationEntityPaginated' from JSON`,
  );
}
