/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Integrations_ConfluenceCloud_SpaceEntity model
 */
export type IntegrationsConfluenceCloudSpaceEntity = {
  id?: number | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const IntegrationsConfluenceCloudSpaceEntity$inboundSchema: z.ZodType<
  IntegrationsConfluenceCloudSpaceEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.number().int()).optional(),
  name: z.nullable(z.string()).optional(),
});
/** @internal */
export type IntegrationsConfluenceCloudSpaceEntity$Outbound = {
  id?: number | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const IntegrationsConfluenceCloudSpaceEntity$outboundSchema: z.ZodType<
  IntegrationsConfluenceCloudSpaceEntity$Outbound,
  z.ZodTypeDef,
  IntegrationsConfluenceCloudSpaceEntity
> = z.object({
  id: z.nullable(z.number().int()).optional(),
  name: z.nullable(z.string()).optional(),
});

export function integrationsConfluenceCloudSpaceEntityToJSON(
  integrationsConfluenceCloudSpaceEntity:
    IntegrationsConfluenceCloudSpaceEntity,
): string {
  return JSON.stringify(
    IntegrationsConfluenceCloudSpaceEntity$outboundSchema.parse(
      integrationsConfluenceCloudSpaceEntity,
    ),
  );
}
export function integrationsConfluenceCloudSpaceEntityFromJSON(
  jsonString: string,
): SafeParseResult<IntegrationsConfluenceCloudSpaceEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IntegrationsConfluenceCloudSpaceEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntegrationsConfluenceCloudSpaceEntity' from JSON`,
  );
}
