/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IntegrationsStatuspageSeverityEntity = {
  severitySlug?: string | null | undefined;
  remoteStatus?: string | null | undefined;
};

/** @internal */
export const IntegrationsStatuspageSeverityEntity$inboundSchema: z.ZodType<
  IntegrationsStatuspageSeverityEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  severity_slug: z.nullable(z.string()).optional(),
  remote_status: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "severity_slug": "severitySlug",
    "remote_status": "remoteStatus",
  });
});
/** @internal */
export type IntegrationsStatuspageSeverityEntity$Outbound = {
  severity_slug?: string | null | undefined;
  remote_status?: string | null | undefined;
};

/** @internal */
export const IntegrationsStatuspageSeverityEntity$outboundSchema: z.ZodType<
  IntegrationsStatuspageSeverityEntity$Outbound,
  z.ZodTypeDef,
  IntegrationsStatuspageSeverityEntity
> = z.object({
  severitySlug: z.nullable(z.string()).optional(),
  remoteStatus: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    severitySlug: "severity_slug",
    remoteStatus: "remote_status",
  });
});

export function integrationsStatuspageSeverityEntityToJSON(
  integrationsStatuspageSeverityEntity: IntegrationsStatuspageSeverityEntity,
): string {
  return JSON.stringify(
    IntegrationsStatuspageSeverityEntity$outboundSchema.parse(
      integrationsStatuspageSeverityEntity,
    ),
  );
}
export function integrationsStatuspageSeverityEntityFromJSON(
  jsonString: string,
): SafeParseResult<IntegrationsStatuspageSeverityEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IntegrationsStatuspageSeverityEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntegrationsStatuspageSeverityEntity' from JSON`,
  );
}
