/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullableActorEntity,
  NullableActorEntity$inboundSchema,
  NullableActorEntity$Outbound,
  NullableActorEntity$outboundSchema,
} from "./nullableactorentity.js";
import {
  NullableRunbooksWebhookDeliveryEntity,
  NullableRunbooksWebhookDeliveryEntity$inboundSchema,
  NullableRunbooksWebhookDeliveryEntity$Outbound,
  NullableRunbooksWebhookDeliveryEntity$outboundSchema,
} from "./nullablerunbookswebhookdeliveryentity.js";

export const NullableRunbooksExecutionStepExecutionEntityState = {
  Initial: "initial",
  Pending: "pending",
  Scheduled: "scheduled",
  Started: "started",
  Dismissed: "dismissed",
  Completed: "completed",
  Errored: "errored",
} as const;
export type NullableRunbooksExecutionStepExecutionEntityState = ClosedEnum<
  typeof NullableRunbooksExecutionStepExecutionEntityState
>;

export type NullableRunbooksExecutionStepExecutionEntityData = {};

export type NullableRunbooksExecutionStepExecutionEntity = {
  state?: NullableRunbooksExecutionStepExecutionEntityState | null | undefined;
  data?: NullableRunbooksExecutionStepExecutionEntityData | null | undefined;
  performedBy?: NullableActorEntity | null | undefined;
  performedAt?: Date | null | undefined;
  scheduledFor?: Date | null | undefined;
  error?: string | null | undefined;
  webhookDelivery?: NullableRunbooksWebhookDeliveryEntity | null | undefined;
};

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntityState$inboundSchema:
  z.ZodNativeEnum<typeof NullableRunbooksExecutionStepExecutionEntityState> = z
    .nativeEnum(NullableRunbooksExecutionStepExecutionEntityState);

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntityState$outboundSchema:
  z.ZodNativeEnum<typeof NullableRunbooksExecutionStepExecutionEntityState> =
    NullableRunbooksExecutionStepExecutionEntityState$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableRunbooksExecutionStepExecutionEntityState$ {
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntityState$inboundSchema` instead. */
  export const inboundSchema =
    NullableRunbooksExecutionStepExecutionEntityState$inboundSchema;
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntityState$outboundSchema` instead. */
  export const outboundSchema =
    NullableRunbooksExecutionStepExecutionEntityState$outboundSchema;
}

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntityData$inboundSchema:
  z.ZodType<
    NullableRunbooksExecutionStepExecutionEntityData,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type NullableRunbooksExecutionStepExecutionEntityData$Outbound = {};

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntityData$outboundSchema:
  z.ZodType<
    NullableRunbooksExecutionStepExecutionEntityData$Outbound,
    z.ZodTypeDef,
    NullableRunbooksExecutionStepExecutionEntityData
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableRunbooksExecutionStepExecutionEntityData$ {
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntityData$inboundSchema` instead. */
  export const inboundSchema =
    NullableRunbooksExecutionStepExecutionEntityData$inboundSchema;
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntityData$outboundSchema` instead. */
  export const outboundSchema =
    NullableRunbooksExecutionStepExecutionEntityData$outboundSchema;
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntityData$Outbound` instead. */
  export type Outbound =
    NullableRunbooksExecutionStepExecutionEntityData$Outbound;
}

export function nullableRunbooksExecutionStepExecutionEntityDataToJSON(
  nullableRunbooksExecutionStepExecutionEntityData:
    NullableRunbooksExecutionStepExecutionEntityData,
): string {
  return JSON.stringify(
    NullableRunbooksExecutionStepExecutionEntityData$outboundSchema.parse(
      nullableRunbooksExecutionStepExecutionEntityData,
    ),
  );
}

export function nullableRunbooksExecutionStepExecutionEntityDataFromJSON(
  jsonString: string,
): SafeParseResult<
  NullableRunbooksExecutionStepExecutionEntityData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      NullableRunbooksExecutionStepExecutionEntityData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'NullableRunbooksExecutionStepExecutionEntityData' from JSON`,
  );
}

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntity$inboundSchema:
  z.ZodType<
    NullableRunbooksExecutionStepExecutionEntity,
    z.ZodTypeDef,
    unknown
  > = z.object({
    state: z.nullable(
      NullableRunbooksExecutionStepExecutionEntityState$inboundSchema,
    ).optional(),
    data: z.nullable(
      z.lazy(() =>
        NullableRunbooksExecutionStepExecutionEntityData$inboundSchema
      ),
    ).optional(),
    performed_by: z.nullable(NullableActorEntity$inboundSchema).optional(),
    performed_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    scheduled_for: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    error: z.nullable(z.string()).optional(),
    webhook_delivery: z.nullable(
      NullableRunbooksWebhookDeliveryEntity$inboundSchema,
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "performed_by": "performedBy",
      "performed_at": "performedAt",
      "scheduled_for": "scheduledFor",
      "webhook_delivery": "webhookDelivery",
    });
  });

/** @internal */
export type NullableRunbooksExecutionStepExecutionEntity$Outbound = {
  state?: string | null | undefined;
  data?:
    | NullableRunbooksExecutionStepExecutionEntityData$Outbound
    | null
    | undefined;
  performed_by?: NullableActorEntity$Outbound | null | undefined;
  performed_at?: string | null | undefined;
  scheduled_for?: string | null | undefined;
  error?: string | null | undefined;
  webhook_delivery?:
    | NullableRunbooksWebhookDeliveryEntity$Outbound
    | null
    | undefined;
};

/** @internal */
export const NullableRunbooksExecutionStepExecutionEntity$outboundSchema:
  z.ZodType<
    NullableRunbooksExecutionStepExecutionEntity$Outbound,
    z.ZodTypeDef,
    NullableRunbooksExecutionStepExecutionEntity
  > = z.object({
    state: z.nullable(
      NullableRunbooksExecutionStepExecutionEntityState$outboundSchema,
    ).optional(),
    data: z.nullable(
      z.lazy(() =>
        NullableRunbooksExecutionStepExecutionEntityData$outboundSchema
      ),
    ).optional(),
    performedBy: z.nullable(NullableActorEntity$outboundSchema).optional(),
    performedAt: z.nullable(z.date().transform(v => v.toISOString()))
      .optional(),
    scheduledFor: z.nullable(z.date().transform(v => v.toISOString()))
      .optional(),
    error: z.nullable(z.string()).optional(),
    webhookDelivery: z.nullable(
      NullableRunbooksWebhookDeliveryEntity$outboundSchema,
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      performedBy: "performed_by",
      performedAt: "performed_at",
      scheduledFor: "scheduled_for",
      webhookDelivery: "webhook_delivery",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableRunbooksExecutionStepExecutionEntity$ {
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntity$inboundSchema` instead. */
  export const inboundSchema =
    NullableRunbooksExecutionStepExecutionEntity$inboundSchema;
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntity$outboundSchema` instead. */
  export const outboundSchema =
    NullableRunbooksExecutionStepExecutionEntity$outboundSchema;
  /** @deprecated use `NullableRunbooksExecutionStepExecutionEntity$Outbound` instead. */
  export type Outbound = NullableRunbooksExecutionStepExecutionEntity$Outbound;
}

export function nullableRunbooksExecutionStepExecutionEntityToJSON(
  nullableRunbooksExecutionStepExecutionEntity:
    NullableRunbooksExecutionStepExecutionEntity,
): string {
  return JSON.stringify(
    NullableRunbooksExecutionStepExecutionEntity$outboundSchema.parse(
      nullableRunbooksExecutionStepExecutionEntity,
    ),
  );
}

export function nullableRunbooksExecutionStepExecutionEntityFromJSON(
  jsonString: string,
): SafeParseResult<
  NullableRunbooksExecutionStepExecutionEntity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      NullableRunbooksExecutionStepExecutionEntity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'NullableRunbooksExecutionStepExecutionEntity' from JSON`,
  );
}
