/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NullableSignalsAPIOnCallStrategyEntity = {
  type?: string | null | undefined;
  handoffTime?: string | null | undefined;
  handoffDay?: string | null | undefined;
  shiftDuration?: string | null | undefined;
};

/** @internal */
export const NullableSignalsAPIOnCallStrategyEntity$inboundSchema: z.ZodType<
  NullableSignalsAPIOnCallStrategyEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.nullable(z.string()).optional(),
  handoff_time: z.nullable(z.string()).optional(),
  handoff_day: z.nullable(z.string()).optional(),
  shift_duration: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "handoff_time": "handoffTime",
    "handoff_day": "handoffDay",
    "shift_duration": "shiftDuration",
  });
});

/** @internal */
export type NullableSignalsAPIOnCallStrategyEntity$Outbound = {
  type?: string | null | undefined;
  handoff_time?: string | null | undefined;
  handoff_day?: string | null | undefined;
  shift_duration?: string | null | undefined;
};

/** @internal */
export const NullableSignalsAPIOnCallStrategyEntity$outboundSchema: z.ZodType<
  NullableSignalsAPIOnCallStrategyEntity$Outbound,
  z.ZodTypeDef,
  NullableSignalsAPIOnCallStrategyEntity
> = z.object({
  type: z.nullable(z.string()).optional(),
  handoffTime: z.nullable(z.string()).optional(),
  handoffDay: z.nullable(z.string()).optional(),
  shiftDuration: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    handoffTime: "handoff_time",
    handoffDay: "handoff_day",
    shiftDuration: "shift_duration",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableSignalsAPIOnCallStrategyEntity$ {
  /** @deprecated use `NullableSignalsAPIOnCallStrategyEntity$inboundSchema` instead. */
  export const inboundSchema =
    NullableSignalsAPIOnCallStrategyEntity$inboundSchema;
  /** @deprecated use `NullableSignalsAPIOnCallStrategyEntity$outboundSchema` instead. */
  export const outboundSchema =
    NullableSignalsAPIOnCallStrategyEntity$outboundSchema;
  /** @deprecated use `NullableSignalsAPIOnCallStrategyEntity$Outbound` instead. */
  export type Outbound = NullableSignalsAPIOnCallStrategyEntity$Outbound;
}

export function nullableSignalsAPIOnCallStrategyEntityToJSON(
  nullableSignalsAPIOnCallStrategyEntity:
    NullableSignalsAPIOnCallStrategyEntity,
): string {
  return JSON.stringify(
    NullableSignalsAPIOnCallStrategyEntity$outboundSchema.parse(
      nullableSignalsAPIOnCallStrategyEntity,
    ),
  );
}

export function nullableSignalsAPIOnCallStrategyEntityFromJSON(
  jsonString: string,
): SafeParseResult<NullableSignalsAPIOnCallStrategyEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NullableSignalsAPIOnCallStrategyEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NullableSignalsAPIOnCallStrategyEntity' from JSON`,
  );
}
