/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullableAuthorEntity,
  NullableAuthorEntity$inboundSchema,
  NullableAuthorEntity$Outbound,
  NullableAuthorEntity$outboundSchema,
} from "./nullableauthorentity.js";

export type ExamplePayload = {};

export type NullableSignalsAPITransposerEntity = {
  name?: string | null | undefined;
  slug?: string | null | undefined;
  examplePayload?: ExamplePayload | null | undefined;
  expression?: string | null | undefined;
  expected?: string | null | undefined;
  website?: string | null | undefined;
  description?: string | null | undefined;
  tags?: Array<string> | null | undefined;
  ingestUrl?: string | null | undefined;
  editable?: boolean | null | undefined;
  createdBy?: NullableAuthorEntity | null | undefined;
  updatedBy?: NullableAuthorEntity | null | undefined;
};

/** @internal */
export const ExamplePayload$inboundSchema: z.ZodType<
  ExamplePayload,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ExamplePayload$Outbound = {};

/** @internal */
export const ExamplePayload$outboundSchema: z.ZodType<
  ExamplePayload$Outbound,
  z.ZodTypeDef,
  ExamplePayload
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExamplePayload$ {
  /** @deprecated use `ExamplePayload$inboundSchema` instead. */
  export const inboundSchema = ExamplePayload$inboundSchema;
  /** @deprecated use `ExamplePayload$outboundSchema` instead. */
  export const outboundSchema = ExamplePayload$outboundSchema;
  /** @deprecated use `ExamplePayload$Outbound` instead. */
  export type Outbound = ExamplePayload$Outbound;
}

export function examplePayloadToJSON(examplePayload: ExamplePayload): string {
  return JSON.stringify(ExamplePayload$outboundSchema.parse(examplePayload));
}

export function examplePayloadFromJSON(
  jsonString: string,
): SafeParseResult<ExamplePayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExamplePayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExamplePayload' from JSON`,
  );
}

/** @internal */
export const NullableSignalsAPITransposerEntity$inboundSchema: z.ZodType<
  NullableSignalsAPITransposerEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  example_payload: z.nullable(z.lazy(() => ExamplePayload$inboundSchema))
    .optional(),
  expression: z.nullable(z.string()).optional(),
  expected: z.nullable(z.string()).optional(),
  website: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  ingest_url: z.nullable(z.string()).optional(),
  editable: z.nullable(z.boolean()).optional(),
  created_by: z.nullable(NullableAuthorEntity$inboundSchema).optional(),
  updated_by: z.nullable(NullableAuthorEntity$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "example_payload": "examplePayload",
    "ingest_url": "ingestUrl",
    "created_by": "createdBy",
    "updated_by": "updatedBy",
  });
});

/** @internal */
export type NullableSignalsAPITransposerEntity$Outbound = {
  name?: string | null | undefined;
  slug?: string | null | undefined;
  example_payload?: ExamplePayload$Outbound | null | undefined;
  expression?: string | null | undefined;
  expected?: string | null | undefined;
  website?: string | null | undefined;
  description?: string | null | undefined;
  tags?: Array<string> | null | undefined;
  ingest_url?: string | null | undefined;
  editable?: boolean | null | undefined;
  created_by?: NullableAuthorEntity$Outbound | null | undefined;
  updated_by?: NullableAuthorEntity$Outbound | null | undefined;
};

/** @internal */
export const NullableSignalsAPITransposerEntity$outboundSchema: z.ZodType<
  NullableSignalsAPITransposerEntity$Outbound,
  z.ZodTypeDef,
  NullableSignalsAPITransposerEntity
> = z.object({
  name: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  examplePayload: z.nullable(z.lazy(() => ExamplePayload$outboundSchema))
    .optional(),
  expression: z.nullable(z.string()).optional(),
  expected: z.nullable(z.string()).optional(),
  website: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  ingestUrl: z.nullable(z.string()).optional(),
  editable: z.nullable(z.boolean()).optional(),
  createdBy: z.nullable(NullableAuthorEntity$outboundSchema).optional(),
  updatedBy: z.nullable(NullableAuthorEntity$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    examplePayload: "example_payload",
    ingestUrl: "ingest_url",
    createdBy: "created_by",
    updatedBy: "updated_by",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableSignalsAPITransposerEntity$ {
  /** @deprecated use `NullableSignalsAPITransposerEntity$inboundSchema` instead. */
  export const inboundSchema = NullableSignalsAPITransposerEntity$inboundSchema;
  /** @deprecated use `NullableSignalsAPITransposerEntity$outboundSchema` instead. */
  export const outboundSchema =
    NullableSignalsAPITransposerEntity$outboundSchema;
  /** @deprecated use `NullableSignalsAPITransposerEntity$Outbound` instead. */
  export type Outbound = NullableSignalsAPITransposerEntity$Outbound;
}

export function nullableSignalsAPITransposerEntityToJSON(
  nullableSignalsAPITransposerEntity: NullableSignalsAPITransposerEntity,
): string {
  return JSON.stringify(
    NullableSignalsAPITransposerEntity$outboundSchema.parse(
      nullableSignalsAPITransposerEntity,
    ),
  );
}

export function nullableSignalsAPITransposerEntityFromJSON(
  jsonString: string,
): SafeParseResult<NullableSignalsAPITransposerEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NullableSignalsAPITransposerEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NullableSignalsAPITransposerEntity' from JSON`,
  );
}
