/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SeverityMatrix_ImpactEntity model
 */
export type NullableSeverityMatrixImpactEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  affectsId?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const NullableSeverityMatrixImpactEntity$inboundSchema: z.ZodType<
  NullableSeverityMatrixImpactEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  affects_id: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "affects_id": "affectsId",
  });
});

/** @internal */
export type NullableSeverityMatrixImpactEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  affects_id?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const NullableSeverityMatrixImpactEntity$outboundSchema: z.ZodType<
  NullableSeverityMatrixImpactEntity$Outbound,
  z.ZodTypeDef,
  NullableSeverityMatrixImpactEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  affectsId: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    affectsId: "affects_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableSeverityMatrixImpactEntity$ {
  /** @deprecated use `NullableSeverityMatrixImpactEntity$inboundSchema` instead. */
  export const inboundSchema = NullableSeverityMatrixImpactEntity$inboundSchema;
  /** @deprecated use `NullableSeverityMatrixImpactEntity$outboundSchema` instead. */
  export const outboundSchema =
    NullableSeverityMatrixImpactEntity$outboundSchema;
  /** @deprecated use `NullableSeverityMatrixImpactEntity$Outbound` instead. */
  export type Outbound = NullableSeverityMatrixImpactEntity$Outbound;
}

export function nullableSeverityMatrixImpactEntityToJSON(
  nullableSeverityMatrixImpactEntity: NullableSeverityMatrixImpactEntity,
): string {
  return JSON.stringify(
    NullableSeverityMatrixImpactEntity$outboundSchema.parse(
      nullableSeverityMatrixImpactEntity,
    ),
  );
}

export function nullableSeverityMatrixImpactEntityFromJSON(
  jsonString: string,
): SafeParseResult<NullableSeverityMatrixImpactEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NullableSeverityMatrixImpactEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NullableSeverityMatrixImpactEntity' from JSON`,
  );
}
