/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NullableRunbooksWebhookDeliveryEntity = {
  headers?: string | null | undefined;
  statusCode?: string | null | undefined;
};

/** @internal */
export const NullableRunbooksWebhookDeliveryEntity$inboundSchema: z.ZodType<
  NullableRunbooksWebhookDeliveryEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  headers: z.nullable(z.string()).optional(),
  status_code: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type NullableRunbooksWebhookDeliveryEntity$Outbound = {
  headers?: string | null | undefined;
  status_code?: string | null | undefined;
};

/** @internal */
export const NullableRunbooksWebhookDeliveryEntity$outboundSchema: z.ZodType<
  NullableRunbooksWebhookDeliveryEntity$Outbound,
  z.ZodTypeDef,
  NullableRunbooksWebhookDeliveryEntity
> = z.object({
  headers: z.nullable(z.string()).optional(),
  statusCode: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NullableRunbooksWebhookDeliveryEntity$ {
  /** @deprecated use `NullableRunbooksWebhookDeliveryEntity$inboundSchema` instead. */
  export const inboundSchema =
    NullableRunbooksWebhookDeliveryEntity$inboundSchema;
  /** @deprecated use `NullableRunbooksWebhookDeliveryEntity$outboundSchema` instead. */
  export const outboundSchema =
    NullableRunbooksWebhookDeliveryEntity$outboundSchema;
  /** @deprecated use `NullableRunbooksWebhookDeliveryEntity$Outbound` instead. */
  export type Outbound = NullableRunbooksWebhookDeliveryEntity$Outbound;
}

export function nullableRunbooksWebhookDeliveryEntityToJSON(
  nullableRunbooksWebhookDeliveryEntity: NullableRunbooksWebhookDeliveryEntity,
): string {
  return JSON.stringify(
    NullableRunbooksWebhookDeliveryEntity$outboundSchema.parse(
      nullableRunbooksWebhookDeliveryEntity,
    ),
  );
}

export function nullableRunbooksWebhookDeliveryEntityFromJSON(
  jsonString: string,
): SafeParseResult<NullableRunbooksWebhookDeliveryEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NullableRunbooksWebhookDeliveryEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NullableRunbooksWebhookDeliveryEntity' from JSON`,
  );
}
