/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullableCalendarsEventEntity,
  NullableCalendarsEventEntity$inboundSchema,
  NullableCalendarsEventEntity$Outbound,
  NullableCalendarsEventEntity$outboundSchema,
} from "./nullablecalendarsevententity.js";
import {
  NullableIncidentEntity,
  NullableIncidentEntity$inboundSchema,
  NullableIncidentEntity$Outbound,
  NullableIncidentEntity$outboundSchema,
} from "./nullableincidententity.js";
import {
  NullablePostMortemsQuestionEntity,
  NullablePostMortemsQuestionEntity$inboundSchema,
  NullablePostMortemsQuestionEntity$Outbound,
  NullablePostMortemsQuestionEntity$outboundSchema,
} from "./nullablepostmortemsquestionentity.js";

/**
 * PostMortems_PostMortemReportEntity model
 */
export type PostMortemsPostMortemReportEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  incidentId?: string | null | undefined;
  createdAt?: Date | null | undefined;
  updatedAt?: Date | null | undefined;
  tagList?: Array<string> | null | undefined;
  additionalDetails?: Array<string> | null | undefined;
  incident?: NullableIncidentEntity | null | undefined;
  questions?: NullablePostMortemsQuestionEntity | null | undefined;
  calendarEvents?: NullableCalendarsEventEntity | null | undefined;
  retrospectiveShim?: boolean | null | undefined;
  retrospectiveId?: string | null | undefined;
  retrospectiveNote?: string | null | undefined;
};

/** @internal */
export const PostMortemsPostMortemReportEntity$inboundSchema: z.ZodType<
  PostMortemsPostMortemReportEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  summary: z.nullable(z.string()).optional(),
  incident_id: z.nullable(z.string()).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  tag_list: z.nullable(z.array(z.string())).optional(),
  additional_details: z.nullable(z.array(z.string())).optional(),
  incident: z.nullable(NullableIncidentEntity$inboundSchema).optional(),
  questions: z.nullable(NullablePostMortemsQuestionEntity$inboundSchema)
    .optional(),
  calendar_events: z.nullable(NullableCalendarsEventEntity$inboundSchema)
    .optional(),
  retrospective_shim: z.nullable(z.boolean()).optional(),
  retrospective_id: z.nullable(z.string()).optional(),
  retrospective_note: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "tag_list": "tagList",
    "additional_details": "additionalDetails",
    "calendar_events": "calendarEvents",
    "retrospective_shim": "retrospectiveShim",
    "retrospective_id": "retrospectiveId",
    "retrospective_note": "retrospectiveNote",
  });
});
/** @internal */
export type PostMortemsPostMortemReportEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  incident_id?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  tag_list?: Array<string> | null | undefined;
  additional_details?: Array<string> | null | undefined;
  incident?: NullableIncidentEntity$Outbound | null | undefined;
  questions?: NullablePostMortemsQuestionEntity$Outbound | null | undefined;
  calendar_events?: NullableCalendarsEventEntity$Outbound | null | undefined;
  retrospective_shim?: boolean | null | undefined;
  retrospective_id?: string | null | undefined;
  retrospective_note?: string | null | undefined;
};

/** @internal */
export const PostMortemsPostMortemReportEntity$outboundSchema: z.ZodType<
  PostMortemsPostMortemReportEntity$Outbound,
  z.ZodTypeDef,
  PostMortemsPostMortemReportEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  summary: z.nullable(z.string()).optional(),
  incidentId: z.nullable(z.string()).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  tagList: z.nullable(z.array(z.string())).optional(),
  additionalDetails: z.nullable(z.array(z.string())).optional(),
  incident: z.nullable(NullableIncidentEntity$outboundSchema).optional(),
  questions: z.nullable(NullablePostMortemsQuestionEntity$outboundSchema)
    .optional(),
  calendarEvents: z.nullable(NullableCalendarsEventEntity$outboundSchema)
    .optional(),
  retrospectiveShim: z.nullable(z.boolean()).optional(),
  retrospectiveId: z.nullable(z.string()).optional(),
  retrospectiveNote: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    incidentId: "incident_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
    tagList: "tag_list",
    additionalDetails: "additional_details",
    calendarEvents: "calendar_events",
    retrospectiveShim: "retrospective_shim",
    retrospectiveId: "retrospective_id",
    retrospectiveNote: "retrospective_note",
  });
});

export function postMortemsPostMortemReportEntityToJSON(
  postMortemsPostMortemReportEntity: PostMortemsPostMortemReportEntity,
): string {
  return JSON.stringify(
    PostMortemsPostMortemReportEntity$outboundSchema.parse(
      postMortemsPostMortemReportEntity,
    ),
  );
}
export function postMortemsPostMortemReportEntityFromJSON(
  jsonString: string,
): SafeParseResult<PostMortemsPostMortemReportEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostMortemsPostMortemReportEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostMortemsPostMortemReportEntity' from JSON`,
  );
}
