/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RetrospectivesReportTemplateEntityElementEntity,
  RetrospectivesReportTemplateEntityElementEntity$inboundSchema,
  RetrospectivesReportTemplateEntityElementEntity$Outbound,
  RetrospectivesReportTemplateEntityElementEntity$outboundSchema,
} from "./retrospectivesreporttemplateentityelemententity.js";

/**
 * Retrospectives_ReportTemplateEntity model
 */
export type RetrospectivesReportTemplateEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  isDefault?: boolean | null | undefined;
  elements?:
    | Array<RetrospectivesReportTemplateEntityElementEntity>
    | null
    | undefined;
  retrospectiveTemplateId?: string | null | undefined;
  createdAt?: Date | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const RetrospectivesReportTemplateEntity$inboundSchema: z.ZodType<
  RetrospectivesReportTemplateEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  is_default: z.nullable(z.boolean()).optional(),
  elements: z.nullable(
    z.array(RetrospectivesReportTemplateEntityElementEntity$inboundSchema),
  ).optional(),
  retrospective_template_id: z.nullable(z.string()).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "is_default": "isDefault",
    "retrospective_template_id": "retrospectiveTemplateId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type RetrospectivesReportTemplateEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  is_default?: boolean | null | undefined;
  elements?:
    | Array<RetrospectivesReportTemplateEntityElementEntity$Outbound>
    | null
    | undefined;
  retrospective_template_id?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
};

/** @internal */
export const RetrospectivesReportTemplateEntity$outboundSchema: z.ZodType<
  RetrospectivesReportTemplateEntity$Outbound,
  z.ZodTypeDef,
  RetrospectivesReportTemplateEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  isDefault: z.nullable(z.boolean()).optional(),
  elements: z.nullable(
    z.array(RetrospectivesReportTemplateEntityElementEntity$outboundSchema),
  ).optional(),
  retrospectiveTemplateId: z.nullable(z.string()).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    isDefault: "is_default",
    retrospectiveTemplateId: "retrospective_template_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

export function retrospectivesReportTemplateEntityToJSON(
  retrospectivesReportTemplateEntity: RetrospectivesReportTemplateEntity,
): string {
  return JSON.stringify(
    RetrospectivesReportTemplateEntity$outboundSchema.parse(
      retrospectivesReportTemplateEntity,
    ),
  );
}
export function retrospectivesReportTemplateEntityFromJSON(
  jsonString: string,
): SafeParseResult<RetrospectivesReportTemplateEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RetrospectivesReportTemplateEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RetrospectivesReportTemplateEntity' from JSON`,
  );
}
