/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";
import {
  RunbooksActionsEntity,
  RunbooksActionsEntity$inboundSchema,
  RunbooksActionsEntity$Outbound,
  RunbooksActionsEntity$outboundSchema,
} from "./runbooksactionsentity.js";

/**
 * Runbooks_ActionsEntityPaginated model
 */
export type RunbooksActionsEntityPaginated = {
  data?: Array<RunbooksActionsEntity> | undefined;
  pagination?: PaginationEntity | undefined;
};

/** @internal */
export const RunbooksActionsEntityPaginated$inboundSchema: z.ZodType<
  RunbooksActionsEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(RunbooksActionsEntity$inboundSchema).optional(),
  pagination: PaginationEntity$inboundSchema.optional(),
});

/** @internal */
export type RunbooksActionsEntityPaginated$Outbound = {
  data?: Array<RunbooksActionsEntity$Outbound> | undefined;
  pagination?: PaginationEntity$Outbound | undefined;
};

/** @internal */
export const RunbooksActionsEntityPaginated$outboundSchema: z.ZodType<
  RunbooksActionsEntityPaginated$Outbound,
  z.ZodTypeDef,
  RunbooksActionsEntityPaginated
> = z.object({
  data: z.array(RunbooksActionsEntity$outboundSchema).optional(),
  pagination: PaginationEntity$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunbooksActionsEntityPaginated$ {
  /** @deprecated use `RunbooksActionsEntityPaginated$inboundSchema` instead. */
  export const inboundSchema = RunbooksActionsEntityPaginated$inboundSchema;
  /** @deprecated use `RunbooksActionsEntityPaginated$outboundSchema` instead. */
  export const outboundSchema = RunbooksActionsEntityPaginated$outboundSchema;
  /** @deprecated use `RunbooksActionsEntityPaginated$Outbound` instead. */
  export type Outbound = RunbooksActionsEntityPaginated$Outbound;
}

export function runbooksActionsEntityPaginatedToJSON(
  runbooksActionsEntityPaginated: RunbooksActionsEntityPaginated,
): string {
  return JSON.stringify(
    RunbooksActionsEntityPaginated$outboundSchema.parse(
      runbooksActionsEntityPaginated,
    ),
  );
}

export function runbooksActionsEntityPaginatedFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksActionsEntityPaginated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunbooksActionsEntityPaginated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksActionsEntityPaginated' from JSON`,
  );
}
