/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SeverityMatrix_ImpactEntity model
 */
export type SeverityMatrixImpactEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  affectsId?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const SeverityMatrixImpactEntity$inboundSchema: z.ZodType<
  SeverityMatrixImpactEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  affects_id: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "affects_id": "affectsId",
  });
});

/** @internal */
export type SeverityMatrixImpactEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  type?: string | null | undefined;
  affects_id?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const SeverityMatrixImpactEntity$outboundSchema: z.ZodType<
  SeverityMatrixImpactEntity$Outbound,
  z.ZodTypeDef,
  SeverityMatrixImpactEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  affectsId: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    affectsId: "affects_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SeverityMatrixImpactEntity$ {
  /** @deprecated use `SeverityMatrixImpactEntity$inboundSchema` instead. */
  export const inboundSchema = SeverityMatrixImpactEntity$inboundSchema;
  /** @deprecated use `SeverityMatrixImpactEntity$outboundSchema` instead. */
  export const outboundSchema = SeverityMatrixImpactEntity$outboundSchema;
  /** @deprecated use `SeverityMatrixImpactEntity$Outbound` instead. */
  export type Outbound = SeverityMatrixImpactEntity$Outbound;
}

export function severityMatrixImpactEntityToJSON(
  severityMatrixImpactEntity: SeverityMatrixImpactEntity,
): string {
  return JSON.stringify(
    SeverityMatrixImpactEntity$outboundSchema.parse(severityMatrixImpactEntity),
  );
}

export function severityMatrixImpactEntityFromJSON(
  jsonString: string,
): SafeParseResult<SeverityMatrixImpactEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SeverityMatrixImpactEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SeverityMatrixImpactEntity' from JSON`,
  );
}
