/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullablePaginationEntity,
  NullablePaginationEntity$inboundSchema,
  NullablePaginationEntity$Outbound,
  NullablePaginationEntity$outboundSchema,
} from "./nullablepaginationentity.js";
import {
  SignalsAPIEscalationPolicyEntity,
  SignalsAPIEscalationPolicyEntity$inboundSchema,
  SignalsAPIEscalationPolicyEntity$Outbound,
  SignalsAPIEscalationPolicyEntity$outboundSchema,
} from "./signalsapiescalationpolicyentity.js";

/**
 * Signals_API_EscalationPolicyEntityPaginated model
 */
export type SignalsAPIEscalationPolicyEntityPaginated = {
  data?: Array<SignalsAPIEscalationPolicyEntity> | null | undefined;
  pagination?: NullablePaginationEntity | null | undefined;
};

/** @internal */
export const SignalsAPIEscalationPolicyEntityPaginated$inboundSchema: z.ZodType<
  SignalsAPIEscalationPolicyEntityPaginated,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.nullable(z.array(SignalsAPIEscalationPolicyEntity$inboundSchema))
    .optional(),
  pagination: z.nullable(NullablePaginationEntity$inboundSchema).optional(),
});
/** @internal */
export type SignalsAPIEscalationPolicyEntityPaginated$Outbound = {
  data?: Array<SignalsAPIEscalationPolicyEntity$Outbound> | null | undefined;
  pagination?: NullablePaginationEntity$Outbound | null | undefined;
};

/** @internal */
export const SignalsAPIEscalationPolicyEntityPaginated$outboundSchema:
  z.ZodType<
    SignalsAPIEscalationPolicyEntityPaginated$Outbound,
    z.ZodTypeDef,
    SignalsAPIEscalationPolicyEntityPaginated
  > = z.object({
    data: z.nullable(z.array(SignalsAPIEscalationPolicyEntity$outboundSchema))
      .optional(),
    pagination: z.nullable(NullablePaginationEntity$outboundSchema).optional(),
  });

export function signalsAPIEscalationPolicyEntityPaginatedToJSON(
  signalsAPIEscalationPolicyEntityPaginated:
    SignalsAPIEscalationPolicyEntityPaginated,
): string {
  return JSON.stringify(
    SignalsAPIEscalationPolicyEntityPaginated$outboundSchema.parse(
      signalsAPIEscalationPolicyEntityPaginated,
    ),
  );
}
export function signalsAPIEscalationPolicyEntityPaginatedFromJSON(
  jsonString: string,
): SafeParseResult<
  SignalsAPIEscalationPolicyEntityPaginated,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SignalsAPIEscalationPolicyEntityPaginated$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SignalsAPIEscalationPolicyEntityPaginated' from JSON`,
  );
}
