/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullableSignalsAPIDestinationEntity,
  NullableSignalsAPIDestinationEntity$inboundSchema,
  NullableSignalsAPIDestinationEntity$Outbound,
  NullableSignalsAPIDestinationEntity$outboundSchema,
} from "./nullablesignalsapidestinationentity.js";

export type SignalsAPIUserNotificationSettingEntity = {
  id?: string | null | undefined;
  notificationType?: string | null | undefined;
  delay?: string | null | undefined;
  notificationPriority?: string | null | undefined;
  destination?: NullableSignalsAPIDestinationEntity | null | undefined;
};

/** @internal */
export const SignalsAPIUserNotificationSettingEntity$inboundSchema: z.ZodType<
  SignalsAPIUserNotificationSettingEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  notification_type: z.nullable(z.string()).optional(),
  delay: z.nullable(z.string()).optional(),
  notification_priority: z.nullable(z.string()).optional(),
  destination: z.nullable(NullableSignalsAPIDestinationEntity$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "notification_type": "notificationType",
    "notification_priority": "notificationPriority",
  });
});
/** @internal */
export type SignalsAPIUserNotificationSettingEntity$Outbound = {
  id?: string | null | undefined;
  notification_type?: string | null | undefined;
  delay?: string | null | undefined;
  notification_priority?: string | null | undefined;
  destination?: NullableSignalsAPIDestinationEntity$Outbound | null | undefined;
};

/** @internal */
export const SignalsAPIUserNotificationSettingEntity$outboundSchema: z.ZodType<
  SignalsAPIUserNotificationSettingEntity$Outbound,
  z.ZodTypeDef,
  SignalsAPIUserNotificationSettingEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  notificationType: z.nullable(z.string()).optional(),
  delay: z.nullable(z.string()).optional(),
  notificationPriority: z.nullable(z.string()).optional(),
  destination: z.nullable(NullableSignalsAPIDestinationEntity$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    notificationType: "notification_type",
    notificationPriority: "notification_priority",
  });
});

export function signalsAPIUserNotificationSettingEntityToJSON(
  signalsAPIUserNotificationSettingEntity:
    SignalsAPIUserNotificationSettingEntity,
): string {
  return JSON.stringify(
    SignalsAPIUserNotificationSettingEntity$outboundSchema.parse(
      signalsAPIUserNotificationSettingEntity,
    ),
  );
}
export function signalsAPIUserNotificationSettingEntityFromJSON(
  jsonString: string,
): SafeParseResult<
  SignalsAPIUserNotificationSettingEntity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SignalsAPIUserNotificationSettingEntity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SignalsAPIUserNotificationSettingEntity' from JSON`,
  );
}
