/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  NullablePublicApiv1IncidentsSuccinctEntity,
  NullablePublicApiv1IncidentsSuccinctEntity$inboundSchema,
  NullablePublicApiv1IncidentsSuccinctEntity$Outbound,
  NullablePublicApiv1IncidentsSuccinctEntity$outboundSchema,
} from "./nullablepublicapiv1incidentssuccinctentity.js";
import {
  NullableRulesRuleEntity,
  NullableRulesRuleEntity$inboundSchema,
  NullableRulesRuleEntity$Outbound,
  NullableRulesRuleEntity$outboundSchema,
} from "./nullablerulesruleentity.js";
import {
  NullableTeamEntityLite,
  NullableTeamEntityLite$inboundSchema,
  NullableTeamEntityLite$Outbound,
  NullableTeamEntityLite$outboundSchema,
} from "./nullableteamentitylite.js";

export type SlimRunbookEntity = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  type?: string | null | undefined;
  createdAt?: Date | null | undefined;
  updatedAt?: Date | null | undefined;
  attachmentRule?: NullableRulesRuleEntity | null | undefined;
  owner?: NullableTeamEntityLite | null | undefined;
  /**
   * categories the runbook applies to
   */
  categories?: Array<string> | null | undefined;
  /**
   * The timestamp when this runbook was last executed
   */
  lastExecutedAt?: Date | null | undefined;
  lastExecutedForIncident?:
    | NullablePublicApiv1IncidentsSuccinctEntity
    | null
    | undefined;
};

/** @internal */
export const SlimRunbookEntity$inboundSchema: z.ZodType<
  SlimRunbookEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  summary: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  updated_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  attachment_rule: z.nullable(NullableRulesRuleEntity$inboundSchema).optional(),
  owner: z.nullable(NullableTeamEntityLite$inboundSchema).optional(),
  categories: z.nullable(z.array(z.string())).optional(),
  last_executed_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  last_executed_for_incident: z.nullable(
    NullablePublicApiv1IncidentsSuccinctEntity$inboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "attachment_rule": "attachmentRule",
    "last_executed_at": "lastExecutedAt",
    "last_executed_for_incident": "lastExecutedForIncident",
  });
});
/** @internal */
export type SlimRunbookEntity$Outbound = {
  id?: string | null | undefined;
  name?: string | null | undefined;
  summary?: string | null | undefined;
  description?: string | null | undefined;
  type?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  attachment_rule?: NullableRulesRuleEntity$Outbound | null | undefined;
  owner?: NullableTeamEntityLite$Outbound | null | undefined;
  categories?: Array<string> | null | undefined;
  last_executed_at?: string | null | undefined;
  last_executed_for_incident?:
    | NullablePublicApiv1IncidentsSuccinctEntity$Outbound
    | null
    | undefined;
};

/** @internal */
export const SlimRunbookEntity$outboundSchema: z.ZodType<
  SlimRunbookEntity$Outbound,
  z.ZodTypeDef,
  SlimRunbookEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  summary: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  type: z.nullable(z.string()).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  updatedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  attachmentRule: z.nullable(NullableRulesRuleEntity$outboundSchema).optional(),
  owner: z.nullable(NullableTeamEntityLite$outboundSchema).optional(),
  categories: z.nullable(z.array(z.string())).optional(),
  lastExecutedAt: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastExecutedForIncident: z.nullable(
    NullablePublicApiv1IncidentsSuccinctEntity$outboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
    attachmentRule: "attachment_rule",
    lastExecutedAt: "last_executed_at",
    lastExecutedForIncident: "last_executed_for_incident",
  });
});

export function slimRunbookEntityToJSON(
  slimRunbookEntity: SlimRunbookEntity,
): string {
  return JSON.stringify(
    SlimRunbookEntity$outboundSchema.parse(slimRunbookEntity),
  );
}
export function slimRunbookEntityFromJSON(
  jsonString: string,
): SafeParseResult<SlimRunbookEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlimRunbookEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlimRunbookEntity' from JSON`,
  );
}
