/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TicketingProjectFieldMapBodyEntity,
  TicketingProjectFieldMapBodyEntity$inboundSchema,
  TicketingProjectFieldMapBodyEntity$Outbound,
  TicketingProjectFieldMapBodyEntity$outboundSchema,
} from "./ticketingprojectfieldmapbodyentity.js";

/**
 * Ticketing_ProjectFieldMapEntity model
 */
export type TicketingProjectFieldMapEntity = {
  id?: string | null | undefined;
  connectionId?: string | null | undefined;
  connectionType?: string | null | undefined;
  ticketingProjectId?: string | null | undefined;
  body?: Array<TicketingProjectFieldMapBodyEntity> | null | undefined;
};

/** @internal */
export const TicketingProjectFieldMapEntity$inboundSchema: z.ZodType<
  TicketingProjectFieldMapEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  connection_id: z.nullable(z.string()).optional(),
  connection_type: z.nullable(z.string()).optional(),
  ticketing_project_id: z.nullable(z.string()).optional(),
  body: z.nullable(z.array(TicketingProjectFieldMapBodyEntity$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "connection_id": "connectionId",
    "connection_type": "connectionType",
    "ticketing_project_id": "ticketingProjectId",
  });
});
/** @internal */
export type TicketingProjectFieldMapEntity$Outbound = {
  id?: string | null | undefined;
  connection_id?: string | null | undefined;
  connection_type?: string | null | undefined;
  ticketing_project_id?: string | null | undefined;
  body?: Array<TicketingProjectFieldMapBodyEntity$Outbound> | null | undefined;
};

/** @internal */
export const TicketingProjectFieldMapEntity$outboundSchema: z.ZodType<
  TicketingProjectFieldMapEntity$Outbound,
  z.ZodTypeDef,
  TicketingProjectFieldMapEntity
> = z.object({
  id: z.nullable(z.string()).optional(),
  connectionId: z.nullable(z.string()).optional(),
  connectionType: z.nullable(z.string()).optional(),
  ticketingProjectId: z.nullable(z.string()).optional(),
  body: z.nullable(z.array(TicketingProjectFieldMapBodyEntity$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
    connectionType: "connection_type",
    ticketingProjectId: "ticketing_project_id",
  });
});

export function ticketingProjectFieldMapEntityToJSON(
  ticketingProjectFieldMapEntity: TicketingProjectFieldMapEntity,
): string {
  return JSON.stringify(
    TicketingProjectFieldMapEntity$outboundSchema.parse(
      ticketingProjectFieldMapEntity,
    ),
  );
}
export function ticketingProjectFieldMapEntityFromJSON(
  jsonString: string,
): SafeParseResult<TicketingProjectFieldMapEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TicketingProjectFieldMapEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TicketingProjectFieldMapEntity' from JSON`,
  );
}
