/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Update the external incident link attributes
 */
export type UpdateIncidentLink = {
  displayText?: string | null | undefined;
  iconUrl?: string | null | undefined;
  hrefUrl?: string | null | undefined;
};

/** @internal */
export const UpdateIncidentLink$inboundSchema: z.ZodType<
  UpdateIncidentLink,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_text: z.nullable(z.string()).optional(),
  icon_url: z.nullable(z.string()).optional(),
  href_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_text": "displayText",
    "icon_url": "iconUrl",
    "href_url": "hrefUrl",
  });
});
/** @internal */
export type UpdateIncidentLink$Outbound = {
  display_text?: string | null | undefined;
  icon_url?: string | null | undefined;
  href_url?: string | null | undefined;
};

/** @internal */
export const UpdateIncidentLink$outboundSchema: z.ZodType<
  UpdateIncidentLink$Outbound,
  z.ZodTypeDef,
  UpdateIncidentLink
> = z.object({
  displayText: z.nullable(z.string()).optional(),
  iconUrl: z.nullable(z.string()).optional(),
  hrefUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    displayText: "display_text",
    iconUrl: "icon_url",
    hrefUrl: "href_url",
  });
});

export function updateIncidentLinkToJSON(
  updateIncidentLink: UpdateIncidentLink,
): string {
  return JSON.stringify(
    UpdateIncidentLink$outboundSchema.parse(updateIncidentLink),
  );
}
export function updateIncidentLinkFromJSON(
  jsonString: string,
): SafeParseResult<UpdateIncidentLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateIncidentLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateIncidentLink' from JSON`,
  );
}
