/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Update a Signals webhook target by ID
 */
export type UpdateSignalsWebhookTarget = {
  /**
   * The webhook target's name.
   */
  name?: string | null | undefined;
  /**
   * An optional detailed description of the webhook target.
   */
  description?: string | null | undefined;
  /**
   * The URL that the webhook target will notify.
   */
  url?: string | null | undefined;
  /**
   * An optional secret we will provide in the `FH-Signature` header
   *
   * @remarks
   * when sending a payload to the webhook target. This key will not be
   * shown in any response once configured.
   */
  signingKey?: string | null | undefined;
};

/** @internal */
export const UpdateSignalsWebhookTarget$inboundSchema: z.ZodType<
  UpdateSignalsWebhookTarget,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  signing_key: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "signing_key": "signingKey",
  });
});
/** @internal */
export type UpdateSignalsWebhookTarget$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
  url?: string | null | undefined;
  signing_key?: string | null | undefined;
};

/** @internal */
export const UpdateSignalsWebhookTarget$outboundSchema: z.ZodType<
  UpdateSignalsWebhookTarget$Outbound,
  z.ZodTypeDef,
  UpdateSignalsWebhookTarget
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
  signingKey: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    signingKey: "signing_key",
  });
});

export function updateSignalsWebhookTargetToJSON(
  updateSignalsWebhookTarget: UpdateSignalsWebhookTarget,
): string {
  return JSON.stringify(
    UpdateSignalsWebhookTarget$outboundSchema.parse(updateSignalsWebhookTarget),
  );
}
export function updateSignalsWebhookTargetFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSignalsWebhookTarget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSignalsWebhookTarget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSignalsWebhookTarget' from JSON`,
  );
}
