/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Update a severity matrix impact
 */
export type UpdateSeverityMatrixImpact = {
  name?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const UpdateSeverityMatrixImpact$inboundSchema: z.ZodType<
  UpdateSeverityMatrixImpact,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type UpdateSeverityMatrixImpact$Outbound = {
  name?: string | null | undefined;
  position?: number | null | undefined;
};

/** @internal */
export const UpdateSeverityMatrixImpact$outboundSchema: z.ZodType<
  UpdateSeverityMatrixImpact$Outbound,
  z.ZodTypeDef,
  UpdateSeverityMatrixImpact
> = z.object({
  name: z.nullable(z.string()).optional(),
  position: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSeverityMatrixImpact$ {
  /** @deprecated use `UpdateSeverityMatrixImpact$inboundSchema` instead. */
  export const inboundSchema = UpdateSeverityMatrixImpact$inboundSchema;
  /** @deprecated use `UpdateSeverityMatrixImpact$outboundSchema` instead. */
  export const outboundSchema = UpdateSeverityMatrixImpact$outboundSchema;
  /** @deprecated use `UpdateSeverityMatrixImpact$Outbound` instead. */
  export type Outbound = UpdateSeverityMatrixImpact$Outbound;
}

export function updateSeverityMatrixImpactToJSON(
  updateSeverityMatrixImpact: UpdateSeverityMatrixImpact,
): string {
  return JSON.stringify(
    UpdateSeverityMatrixImpact$outboundSchema.parse(updateSeverityMatrixImpact),
  );
}

export function updateSeverityMatrixImpactFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSeverityMatrixImpact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSeverityMatrixImpact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSeverityMatrixImpact' from JSON`,
  );
}
