name: Auto Approve and Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'Auto-merge workflow')
    
    steps:
      - name: Auto approve and merge
        run: |
          echo "Auto-merging PR #${{ github.event.pull_request.number }}"
          
          # Approve
          gh pr review ${{ github.event.pull_request.number }} --approve
          
          # Enable auto-merge
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}