name: Auto Approve and Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    # Check commit author or PR title since actor will be the person who triggered
    if: |
      contains(github.event.pull_request.title, 'Test: Auto-merge workflow') ||
      github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Check PR Details
        id: check-pr
        run: |
          echo "Checking if this PR should be auto-merged..."
          
          # Get the commit author of the head commit
          COMMIT_AUTHOR=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }} \
            --jq '.commit.author.name')
          
          echo "Commit author: $COMMIT_AUTHOR"
          echo "PR title: ${{ github.event.pull_request.title }}"
          
          # Check if this is a bot commit
          if [[ "$COMMIT_AUTHOR" == "github-actions[bot]" ]] || \
             [[ "${{ github.event.pull_request.title }}" == "Test: Auto-merge workflow" ]]; then
            echo "should_proceed=true" >> $GITHUB_OUTPUT
          else
            echo "should_proceed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Approve PR
        if: steps.check-pr.outputs.should_proceed == 'true'
        run: |
          # Create approval review
          gh pr review ${{ github.event.pull_request.number }} \
            --approve \
            --body "Auto-approved by workflow"
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
          
      - name: Enable Auto-merge
        if: steps.check-pr.outputs.should_proceed == 'true'
        run: |
          # Enable auto-merge
          gh pr merge ${{ github.event.pull_request.number }} \
            --auto \
            --merge \
            --delete-branch
            
          # Check status
          echo "Auto-merge status:"
          gh pr view ${{ github.event.pull_request.number }} --json autoMergeRequest
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}