name: Create Test PR for Auto-Merge
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name for test PR'
        default: 'test-auto-merge'
        required: false
        type: string
  push:
    branches: [auto-approve-merge]

jobs:
  create-test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: auto-approve-merge
      
      - name: Create test file
        run: |
          echo "Test auto-merge at $(date)" > test-auto-merge.txt
          echo "This file can be deleted after testing" >> test-auto-merge.txt
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "test: auto-merge functionality"
          title: "Test: Auto-merge workflow"
          body: |
            This is a test PR to verify auto-merge functionality.
            - Created by: github-actions[bot]
            - Should trigger: auto-approve and merge workflow
            - Can be closed if auto-merge fails
          branch: ${{ inputs.branch_name || 'test-auto-merge' }}-${{ github.run_number }}
          base: auto-approve-merge
          delete-branch: true
          draft: false